### ISSUE TITLE
Getting empty responses from OPA engine for no reason at all..

### ISSUE THREAD

**Issue by ParasharaRamesh** [open-policy-agent/opa#3125] opened 2021-02-05 05:56 UTC

**Comment by tsandall** [comment] 2021-02-05 14:14
@ParasharaRamesh thanks for the detailed write up. The `{}` response to GET and POST requests (to `/v1/data/<some_path>`, I assume) indicates the requested document was _undefined_. The value could have been undefined for a couple reasons:

1. The rules that generate the document at that path were not loaded.
2. The rules that generate the document at the path were loaded but did not have a default value and could not be satisfied.

One way to debug this would to be to enable OPA's decision logging feature and see if you can reproduce the issue offline. The decision log will contain:

* The value of the `input` document sent by the client
* The response from OPA
* The revision of the bundles loaded in OPA at the time when the decision was made

That should help narrow down the problem. Either:

* Bundles you expect to be loaded are not
* The rules you expect to generate values are not

Or, you are not able to reproduce the issue and it points to a runtime problem inside of OPA.

One other thing you could try is to enable provenance and tracing information on client queries:

e.g., `POST /v1/data/a/b/c/d?provenance&explain=full&pretty=true`.

Note: Full tracing can be expensive so depending on the request rate into OPA you might want to just use the `fails` explanation which might be enough.

**Comment by tsandall** [comment] 2021-02-23 20:19
Closing this issue as the original description has been removed.

**Closed by tsandall** 2021-02-23 20:19 UTC
Labels: waiting-for-response
