### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by yuvalamar** [open-policy-agent/opa#1827] opened 2019-10-06 14:36 UTC
# Expected Behavior
Opa should not panic and exit

# Actual Behavior
panic 

# Steps to Reproduce the Problem

during everyday operation, we saw panic in the log 

could be related to : https://github.com/open-policy-agent/opa/issues/1666 

# Additional Info
opa version : 0.13.4

[panic_opa.txt](https://github.com/open-policy-agent/opa/files/3694495/panic_opa.txt)

**Comment by tsandall** [comment] 2019-10-07 23:50
@yuvalamar thanks for filing this. The panic appears to be caused by the same issue as #1828 which is fixed in v0.14.2.

**Closed by tsandall** 2019-10-07 23:50 UTC
