### ISSUE TITLE
show all failures when running `opa test --coverage`

### ISSUE THREAD

**Issue by grosser** [open-policy-agent/opa#2505] opened 2020-06-30 20:10 UTC
currently it stops after the first failure which makes it hard to see what failed ... prefer keeping the same output as `opa test` produces (show all failed tests)

**Comment by eliw00d** [comment] 2020-06-30 20:47
The same is true with `--threshold float`.

**Comment by tsandall** [comment] 2020-07-07 16:53
I'm going to close this because it's a dupe of #2139 though the description is slightly different. OPA should just run all of the tests and report the coverage regardless of whether there were failures or errors.

**Closed by tsandall** 2020-07-07 16:53 UTC
