### ISSUE TITLE
'opa build' creates bundles with beginning-of-epoch time stamps

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#3013] opened 2020-12-16 19:56 UTC
## Expected Behavior

The tarballs created using `opa build` have timestamps. They should correlate to something, like the moment the bundle was created.

## Actual Behavior

See https://github.com/open-policy-agent/opa/issues/3007#issuecomment-745412930 for example, it's the beginning of the unix epoch, 1970/01/01, 00:00 -- what you get if you don't provide a time, I suppose.

## Steps to Reproduce the Problem

Build any bundle, examine it using `tar tzvf bundle.tar.gz`

## Additional Info

- Still present in 0.25.2.

**Comment by srenatus** [comment] 2020-12-17 19:18
There's value in producing the *exact same bundle* if run twice with the same input data. Setting timestamps that are not derived from the input data, but correspond to the time of bundle creating, needlessly breaks that.

So, while I'm not certain that our bundle creation is 100% reproducible at the moment, the approach taken in #3018 would definitely hinder this, and thus is wrong 😄

**Comment by tsandall** [comment] 2021-02-23 17:46
I'm going to close this issue because I feel like we concluded that it's "working as intended" for now. We can revisit in the future if there's a better option.

**Closed by tsandall** 2021-02-23 17:46 UTC
Labels: enhancement, good first issue, usability
