### ISSUE TITLE
Seeing lots of TLS handshake errors in OPA logs

### ISSUE THREAD

**Issue by Scott-Wallace-ConnectedLab** [open-policy-agent/opa#710] opened 2018-04-18 20:51 UTC
I have been following through a tutorial on setting up OPA on my Kube 1.8 cluster. Once I get the webhook going and Kube-mgmt to pass in a policy to OPA, I've noticed my logs are filled with TLS handshake errors.

`2018/04/18 17:34:10 http: TLS handshake error from {ip:port}: remote error: tls: bad certificate`
`2018/04/18 17:34:10 http: TLS handshake error from {ip:port}: remote error: tls: bad certificate`

Diving into the IP addresses in the logs, they are my tunl0 addresses from my nodes.

So far I've tried moving the ca.crt that gets mounted on the pod from our cluster into `/usr/local/share/ca-certificates/` and then running `update-ca-certificates`, but no luck. Also tried the cert creation step in the tutorial with my private key from the cluster, but also no luck.

Have you come across anything similar to this issue before? Couldn't find any other occurrences of this online.

Tutorial link: https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/04-path-security-and-networking/403-admission-policy

**Comment by tsandall** [comment] 2018-04-18 21:31
@Scott-Wallace-ConnectedLab this may be caused by the certificate generation steps in the upstream docs. There is a slightly different version in this fork: https://github.com/tim-styra/aws-workshop-for-kubernetes/tree/master/admission-policy#step-2-deploy-opa-on-kubernetes. These changes haven't been upstreamed yet (but they should be.)

The problem addressed in the fork is that common name (CN) in the certificate's subject does not match the name of the Kubernetes service: https://github.com/tim-styra/aws-workshop-for-kubernetes/pull/1/files#diff-197f03f2e7be54b6aba077caec76e1d8R102.

You can try generating the OPA certificates and then redeploying OPA. Hopefully this will fix the issue you're seeing.

**Comment by tsandall** [comment] 2018-04-23 14:58
Closing this for now. The fixes to the guide have been upstreamed. 

https://github.com/aws-samples/aws-workshop-for-kubernetes/pull/423
https://github.com/aws-samples/aws-workshop-for-kubernetes/pull/422

**Closed by tsandall** 2018-04-23 14:58 UTC
