### ISSUE TITLE
OPA timing out installed via Helm

### ISSUE THREAD

**Issue by steve21168** [open-policy-agent/opa#1942] opened 2019-12-04 17:34 UTC
# Expected Behavior
Helm chart to install successfully and use configmap with rules to validate API requests

# Actual Behavior
Helm chart installs successfully and requests to the API timeout attempting to use webhooks to OPA

# Steps to Reproduce the Problem

  1.  Install helm chart with given value overrides

# Additional Info
Platform: EKS
Kubernetes version: 1.14
Helm: stable/opa  1.12.0, Values below

Hi I’m having trouble installing OPA in my EKS cluster from the helm chart.  The chart installs, the mgmt container seems to annotate my rules from the configmap but requests to the API seem to timeout using OPA as the admission controller.  Get/Delete requests to the kube-api seem to work okay but it seems like all my create requests will timeout attempting to validate with OPA

Reviewing my logs
My Kubernetes API Logs show:

> failed calling webhook "webhook.openpolicyagent.org": Post https://opa.kube-system.svc:443/?timeout=30s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)

The mgmt container shows:

> time="2019-12-04T17:07:23Z" level=error msg="Failed to openpolicyagent.org/policy-status for kube-system/image-policy: Timeout: request did not complete within requested timeout 30s"

The opa container only shows logs of the health checks which are all returning 200s

The config map image-policy is the one policy I’ve written and the annotation has been added:

>  annotations:
      openpolicyagent.org/policy-status: '{"status":"ok"}'

I’ve also tested my rego policy locally and it works as intended.

Values overrides:
```
admissionControllerRules:
  - operations: ["*"]
    apiGroups: ["*"]
    apiVersions: ["*"]
    resources: ["*"]

mgmt:
  enabled: true
  configmapPolicies:
    enabled: true
    namespaces: [kube-system]
    requireLabel: true

resources: {}

rbac:
  create: true
  rules:
    cluster:
    - apiGroups:
        - ""
      resources:
      - configmaps
      verbs:
      - get
      - list
      - watch
      - patch
      - update

serviceAccount:
  create: true
  name: opa
```

Thanks for your help!

**Comment by tsandall** [comment] 2019-12-04 20:08
This error indicates that the API server cannot reach OPA or that OPA is not responding:

```
failed calling webhook "webhook.openpolicyagent.org": Post https://opa.kube-system.svc:443/?timeout=30s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

Do you see **ANY** `POST` requests in the OPA log? Tthe PUT requests and health checks are all coming from the same pod so just ignore those.)

One thing you could try that would help diagnose the problem is to query the OPA API directly (e.g., using `curl -X POST https://opa.kube-system.svc:443`.) Try running this from the same node as OPA or another node, etc.  Perhaps there are security group rules preventing the apiserver from contacting OPA?

**Comment by steve21168** [comment] 2019-12-05 18:56
@tsandall Thanks for your response.   Since last speaking I've updated my cluster to now use EKS managed node pools (unrelated to this issue).  I'm still having issues albeit slightly different - sorry for the switchup I wont be making any more changes while debugging this!

My CREATE requests are no longer timing out but they're also not validating and the Kube master is still showing errors

Now in the Kube API logs I see

> Failed calling webhook, failing open webhook.openpolicyagent.org: failed calling webhook "webhook.openpolicyagent.org": the server could not find the requested resource


I am able to reach OPA via a post to the service (using insecure to avoid CA validation):
```
/ # curl -X POST --insecure  https://opa.kube-system.svc:443

{
  "code": "undefined_document",
  "message": "document missing or undefined: data.system.main"
}
```

OPA is receiving POST requests but returning 404s.  From the logs
```
[INFO] Sent response.
  req_path = "/"
  resp_status = 404
  resp_bytes = 99
  resp_duration = 2.088172
  client_addr = "10.99.4.246:50542"
  req_id = 356
  req_method = "POST"

[INFO] Received request.
  req_path = "/"
  client_addr = "10.99.11.89:55604"
  req_id = 357
  req_method = "POST"
```

I also want to show you the ValidatingWebhookConfiguration as I believe this is the webhook being referenced by the master logs:
```
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: "2019-12-05T18:40:00Z"
  generation: 1
  labels:
    app: opa
    chart: opa-1.12.0
    heritage: Helm
    release: opa
  name: opa
  resourceVersion: "25277938"
  selfLink: /apis/admissionregistration.k8s.io/v1beta1/validatingwebhookconfigurations/opa
  uid: a4d395ce-178e-11ea-8631-0e5ca7ddc681
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: CA-HERE
    service:
      name: opa
      namespace: kube-system
  failurePolicy: Ignore
  name: webhook.openpolicyagent.org
  namespaceSelector:
    matchExpressions:
    - key: openpolicyagent.org/webhook
      operator: NotIn
      values:
      - ignore
  rules:
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - '*'
    resources:
    - '*'
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30
```

**Comment by patrick-east** [comment] 2019-12-09 21:47
> {
>   "code": "undefined_document",
>   "message": "document missing or undefined: data.system.main"
> }

Indicates that OPA is up and running but there is not a policy that defines `data.system.main`, so you get a 404.

What policies do you have installed?

Historically there was a bundle that got pulled in and defined some defaults.. however it looks like https://github.com/helm/charts/pull/17947 changed that a couple months ago. So now, at a glance, I don't think that a install with defaults will actually work until policies are added into the system.

**Comment by patrick-east** [comment] 2019-12-09 23:59
https://github.com/helm/charts/pull/19480 Corrects the default values.yaml for the helm chart.

**Comment by tsandall** [comment] 2020-01-09 16:34
Can we close this now that https://github.com/helm/charts/pull/19480 has been merged?

**Comment by patrick-east** [comment] 2020-01-09 17:26
Should be able to.

@steve21168 have you had a chance to try out the newer helm chart? Or with adding the required policies in?

**Comment by tsandall** [comment] 2020-02-11 14:15
Closing this due to inactivity.

**Closed by tsandall** 2020-02-11 14:15 UTC
Labels: question
