### ISSUE TITLE
"Overlapping roots problem" With bundles appearing only on the linux executable for latest versions

### ISSUE THREAD

**Issue by Rohit-R-B** [open-policy-agent/opa#6584] opened 2024-02-12 06:28 UTC
Hi I'm working on a project that uses multiple bundles. One of them is a local bjndle and is run by OPA linux executable. 

The local bundle contains roots of the sort "foo/bar".

The incoming bundle contains data in the hierarchy "foo/baz". It contains a  .manifest containing roots as the same. 

We want the data variable to look like 
{foo: {
     bar: {...},
     baz: {...}
}}

This works locally on the mac with the latest version, but on the linux server it doesn't because of the overlapping roots problem. 

It was working with older versions of the linux executable which we've been using until now and trying to upgrade from. 

Thank you, 
Rohit

**Comment by srenatus** [comment] 2024-02-12 06:38
Would you be able to figure out what the "old version" here was? What are the command line calls you've used to try it locally?

**Comment by Rohit-R-B** [comment] 2024-02-12 11:14
Old version was 0.37.1 

We just use opa run both places

**Comment by srenatus** [comment] 2024-02-12 11:16
Can you share your manifest files, or an [MRE](https://en.wikipedia.org/wiki/Minimal_reproducible_example)?

**Comment by Rohit-R-B** [comment] 2024-02-12 11:33
In the incoming bundle it's as simple as 
{
   "roots":[" foo/baz"], 
   "revisions": ""
}

and the local bundle doesn't have a  .manifest - which causes no error locally, but only while it's executed in the server.

**Comment by srenatus** [comment] 2024-02-12 12:18
> and the local bundle doesn't have a .manifest - which causes no error locally, but only while it's executed in the server.

Hmm a bundle without a manifest implicitly has `roots: ""`, i.e. everything. Can you try declaring the proper roots for both the local and the "incoming" bundle?

> Old version was 0.37.1

That very old. Could be that some bug was changed in between then and now -- since overlapping roots **should** be forbidden.

An MRE here would be a sequence of calls and setup things to reproducibly get to the error. While you've outlined the situation, there are still a few gaps to fill when trying to reproduce it, and the details matter. 😅

**Comment by Rohit-R-B** [comment] 2024-02-12 13:30
If bundle1 contains 
{foo: {
bar: {...}
}} with default roots

And bundle2 contains
{foo: {
bazz: {...}
}} with "foo/bazz" As the root


Does that constitute overlapping roots?

**Comment by srenatus** [comment] 2024-02-12 13:34
> Does that constitute overlapping roots?

Yes, "default roots" means "", **everything**. So "foo/bazz" overlaps with "everything", because _everything_ overlaps with everything. It wouldn't overlap if bundle1 would declare its roots as `["foo/bar"]`.

**Comment by ashutosh-narkar** [comment] 2024-02-12 17:05
Closing this issue. As Stephan mentioned above if you declare your roots in the manifest the bundles will not overlap. Feel free to start a [Discussion](https://github.com/orgs/open-policy-agent/discussions) if you have more questions. Thanks!

**Closed by ashutosh-narkar** 2024-02-12 17:05 UTC
Labels: bug
