### ISSUE TITLE
Unexpect "var requires evaluation" with the same input

### ISSUE THREAD

**Issue by zargex** [open-policy-agent/opa#2047] opened 2020-01-30 14:13 UTC
# Expected Behavior
Return always the same array

# Actual Behavior
It works the first time only, if I try again I get
```
{
  "code": "internal_error",
  "message": "var requires evaluation"
}
```

# Steps to Reproduce the Problem

  1. Deploy the helm chart in minikube, I am using port-forwarding. Push this policy
```
package example.test

val := "test"
servers[id] {
	id := data.kubernetes.persistentvolumeclaims["opa-example"][_].spec.resources.requests.storage
}

storageClass := "multik8s-nfs-storage"
tenant := "opa-example"

current_usage[storage] {
    storageClass = data.kubernetes.persistentvolumeclaims[tenant][pvcname].spec.storageClassName
    storage := data.kubernetes.persistentvolumeclaims[tenant][pvcname].spec.resources.requests.storage
}

normalized_usage[bytes] {
    bytes = units.parse_bytes(replace(current_usage[_], `i`, `iB`))
}

storage_result[asd] = name {
    asd := data.kubernetes.persistentvolumeclaims[tenantns][name].spec.resources.requests.storage
} 
```
`curl -X PUT -i -k --data-binary @example.txt -H "Content-Type: text/plain" $OPA/v1/policies/test1`
 

 2. Run some queries 
This is the `input.json`
```
{
  "input": {
    "kind": "AdmissionReview",
    "apiVersion": "admission.k8s.io/v1beta1",
    "request": {
        "kind": {
          "group": "",
          "version": "v1",
          "kind": "PersistentVolumeClaim"
        },
        "resource": {
          "group": "",
          "version": "v1",
          "resource": "PersistentVolumeClaim"
        },
        "namespace": "opa-example",
        "operation": "CREATE",
        "userInfo": {
          "username": "system:serviceaccount:kube-system:replicaset-controller",
          "uid": "439dea65-3e4e-4fa8-b5f8-8fdc4bc7cf53",
          "groups": [
            "system:serviceaccounts",
            "system:serviceaccounts:kube-system",
            "system:authenticated"
          ]
        },
        "object": {
            "apiVersion": "v1",
            "kind": "PersistentVolumeClaim",
            "metadata": {
                "creationTimestamp": "2020-01-28T19:32:40Z",
                "finalizers": [
                    "kubernetes.io/pvc-protection"
                ],
                "name": "pvc-test-2gi",
                "namespace": "opa-example",
                "resourceVersion": "1926",
                "selfLink": "/api/v1/namespaces/opa-example/persistentvolumeclaims/pvc-test-2gi",
                "uid": "c19b468a-4200-11ea-acaf-00155d380124"
            },
            "spec": {
                "accessModes": [
                    "ReadWriteOnce"
                ],
                "resources": {
                    "requests": {
                        "storage": "2Gi"
                    }
                },
                "storageClassName": "multik8s-nfs-storage",
                "volumeMode": "Filesystem"
            },
            "status": {
                "phase": "Pending"
            }
        }
    }
}
}
```
`curl -k -i -d @input.json -H "Content-Type: application/json" $OPA/v1/data/example/test/current_usage?pretty=true`

  3. Run the first time:
```
"result": [
    "1Gi",
    "200Mi",
    "2Gi"
  ]
```
The second time:
```
{
  "code": "internal_error",
  "message": "var requires evaluation"
}
```

# Additional Info
The helm chart uses this images
image: openpolicyagent/opa
**imageTag: 0.16.1**
image: openpolicyagent/kube-mgmt
**imageTag: "0.11"**

Another thing is if I change the line `storage := data.kubernetes.persistentvolumeclaims[tenant][pvcname].spec.resources.requests.storage` by `storage = data.kubernetes.persistentvolumeclaims[tenant][pvcname].spec.resources.requests.storage` (**change the assignation by unification**) , it will return the same array and it will works as I expect.

I don't know why.

**Comment by tsandall** [comment] 2020-02-24 14:31
@zargex there was a bug in v0.16.0 that would cause this error if you queried with the `explain` flag. The bug was fixed in v0.16.2. I'm not able to reproduce the issue without using the `explain` flag at least once.

For example:

```
# start OPA v0.16.1
torin:~/scratch/issue-2047$ docker run -it --rm -p 8181:8181 openpolicyagent/opa:0.16.1 run -s
```

```
# load policy
torin:~/scratch/issue-2047$ curl --data-binary @policy.rego localhost:8181/v1/policies/test -X PUT
{}

# load data
torin:~/scratch/issue-2047$ cur--data-binary @data.json localhost:8181/v1/data -X PUT

# execute query repeatedly
torin:~/scratch/issue-2047$ curl 'localhost:8181/v1/data/example/test/current_usage?pretty' -d @input.json
{
  "result": [
    "10MB"
  ]
}
torin:~/scratch/issue-2047$ curl 'localhost:8181/v1/data/example/test/current_usage?pretty' -d @input.json
{
  "result": [
    "10MB"
  ]
}
torin:~/scratch/issue-2047$ curl 'localhost:8181/v1/data/example/test/current_usage?pretty' -d @input.json
{
  "result": [
    "10MB"
  ]
}
```

Finally produce the issue by enabling explanations:

```
torin:~/scratch/issue-2047$ curl 'localhost:8181/v1/data/example/test/current_usage?pretty&explain=full' -d @input.json
{
  "explanation": [
    "Enter data.example.test.current_usage = _",
    "| Eval data.example.test.current_usage = _",
    "| Index data.example.test.current_usage = _ (matched 1 rule)",
    "| Enter data.example.test.current_usage",
    "| | Eval __local6__ = data.example.test.tenant",
    "| | Index __local6__ = data.example.test.tenant (matched 1 rule)",
    "| | Enter data.example.test.tenant",
    "| | | Eval true",
    "| | | Exit data.example.test.tenant",
    "| | Eval data.example.test.storageClass = data.kubernetes.persistentvolumeclaims[__local6__][pvcname].spec.storageClassName",
    "| | Index data.example.test.storageClass = data.kubernetes.persistentvolumeclaims[__local6__][pvcname].spec.storageClassName (matched 1 rule)",
    "| | Enter data.example.test.storageClass",
    "| | | Eval true",
    "| | | Exit data.example.test.storageClass",
    "| | Eval __local7__ = data.example.test.tenant",
    "| | Index __local7__ = data.example.test.tenant (matched 1 rule)",
    "| | Eval storage = data.kubernetes.persistentvolumeclaims[__local7__][pvcname].spec.resources.requests.storage",
    "| | Exit data.example.test.current_usage",
    "| Redo data.example.test.current_usage",
    "| | Redo storage = data.kubernetes.persistentvolumeclaims[__local7__][pvcname].spec.resources.requests.storage",
    "| | Redo __local7__ = data.example.test.tenant",
    "| | Redo data.example.test.storageClass = data.kubernetes.persistentvolumeclaims[__local6__][pvcname].spec.storageClassName",
    "| | Redo data.example.test.storageClass",
    "| | | Redo true",
    "| | Redo __local6__ = data.example.test.tenant",
    "| | Redo data.example.test.tenant",
    "| | | Redo true",
    "| Exit data.example.test.current_usage = _",
    "Redo data.example.test.current_usage = _",
    "| Redo data.example.test.current_usage = _"
  ],
  "result": [
    "10MB"
  ]
}

# this query will fail...
torin:~/scratch/issue-2047$ curl 'localhost:8181/v1/data/example/test/current_usage?pretty&explain=full' -d @input.json
{
  "code": "internal_error",
  "message": "var requires evaluation"
}
```

Since I'm not able to reproduce the issue without enabling explanations and the issue with explanations is fixed, I'm going to close this bug. If you're able to provide steps to reproduce without explanations, we can reopen this.

**Closed by tsandall** 2020-02-24 14:31 UTC
