### ISSUE TITLE
Bundle server configuration with client credentials grant doesn't work

### ISSUE THREAD

**Issue by LionOnTheChase** [open-policy-agent/opa#6050] opened 2023-06-26 12:08 UTC
## Short description 
I have configured OPA to fetch bundles from bundle server. I used client credentials grant type for fetching token from authorization server. 

But OPA is not able to fetch the token from authorization server. 

On authorization server logs, I found that client_id is blank. 

{"timestamp":"2023-06-26T11:15:49.859Z","message":"Client id is blank","level":"ERROR","remote-host ":"3.17.212.81","trace.id":"66ac35fee59950515abbb7739af16d90","remote-addr":"3.17.212.81","query-string":"","parameter-map":"grant_type = [client_credentials], isolation_ids = [a21a1909-c664-41be-bfc5-9a3ce0dae52c]","isolationID":"","remote-port":"60105","request-url":"https://somedomain-frontend-us-east-2.cluster.integration.pegaservice.net/uas/oauth/token","span.id":"1fb34f2afdb474bb"}

 Following is the error I see in OPA logs:

 {“level”:“warning”,“msg”:“OPA running with uid or gid 0. Running OPA with root privileges is not recommended.“,”time”:“2023-06-26T11:50:32Z”}
                                   {“level”:“info”,“msg”:“Starting bundle loader.“,”name”:“storagesvc”,“plugin”:“bundle”,“time”:“2023-06-26T11:50:32Z”}
                                   {“level”:“info”,“msg”:“Starting decision logger.“,”plugin”:“decision_logs”,“time”:“2023-06-26T11:50:32Z”}
                                   {“level”:“info”,“msg”:“Tracer created”,“time”:“2023-06-26T11:50:32Z”}                                                               {“addr”:“:9191”,“dry-run”:false,“enable-reflection”:false,“level”:“info”,“msg”:“Starting gRPC server.“,”path”:“istio/authz/allow”,“query”:“”,“time”:“2023-06-26T11:50:32Z”}
     {“level”:“error”,“msg”:“Bundle load failed: request failed: error in response from OAuth2 token endpoint: “,”name”:“storagesvc”,“plugin”:“bundle”,“time”:“2023-06-26T11:50:32Z”}
{“level”:“error”,“msg”:“Bundle load failed: request failed: error in response from OAuth2 token endpoint: “,”name”:“storagesvc”,“plugin”:“bundle”,“time”:“2023-06-26T11:50:32Z”}
{“level”:“error”,“msg”:“Bundle load failed: request failed: error in response from OAuth2 token endpoint: “,”name”:“storagesvc”,“plugin”:“bundle”,“time”:“2023-06-26T11:50:32Z”}
{“level”:“error”,“msg”:“Bundle load failed: request failed: error in response from OAuth2 token endpoint: “,”name”:“storagesvc”,“plugin”:“bundle”,“time”:“2023-06-26T11:50:33Z”}
{“client_addr”:“127.0.0.1:34482”,“level”:“info”,“msg”:“Received request.“,”req_id”:1,“req_method”:“GET”,“req_path”:“/metrics”,“time”:“2023-06-26T11:50:33Z”}
                    {“client_addr”:“127.0.0.1:34482",“level”:“info”,“line”:“/authzConfig/systemPolicy.rego:8",“msg”:“Incoming request:  [\“metrics\“]”,“req_id”:1,“req_method”:“GET”,“req_path”:“/metrics”,“time”:“2023-06-26T11:50:33Z”}                                                   {“client_addr”:“127.0.0.1:34482",“level”:“info”,“line”:“/authzConfig/systemPolicy.rego:34",“msg”:“Request match metrics endpoint”,“req_id”:1,“req_method”:“GET”,“req_path”:“/metrics”,“time”:“2023-06-26T11:50:33Z”}                                                    {“client_addr”:“127.0.0.1:34482”,“level”:“info”,“msg”:“Sent response.“,”req_id”:1,“req_method”:“GET”,“req_path”:“/metrics”,“resp_bytes”:4249,“resp_duration”:2.800963,“resp_status”:200,“time”:“2023-06-26T11:50:33Z”}                                                  {“level”:“error”,“msg”:“Bundle load failed: request failed: error in response from OAuth2 token endpoint: “,”name”:“storagesvc”,“plugin”:“bundle”,“time”:“2023-06-26T11:50:33Z”}
{“level”:“error”,“msg”:“Bundle load failed: request failed: error in response from OAuth2 token endpoint: “,”name”:“storagesvc”,“plugin”:“bundle”,“time”:“2023-06-26T11:50:34Z”}
{“level”:“error”,“msg”:“Bundle load failed: request failed: error in response from OAuth2 token endpoint: “,”name”:“storagesvc”,“plugin”:“bundle”,“time”:“2023-06-26T11:50:35Z”}
{“level”:“error”,“msg”:“Bundle load failed: request failed: error in response from OAuth2 token endpoint: “,”name”:“storagesvc”,“plugin”:“bundle”,“time”:“2023-06-26T11:50:37Z”}
{“level”:“error”,“msg”:“Bundle load failed: request failed: error in response from OAuth2 token endpoint: “,”name”:“storagesvc”,“plugin”:“bundle”,“time”:“2023-06-26T11:50:39Z”}
{“level”:“error”,“msg”:“Bundle load failed: request failed: error in response from OAuth2 token endpoint: “,”name”:“storagesvc”,“plugin”:“bundle”,“time”:“2023-06-26T11:50:44Z”}
{“client_addr”:“127.0.0.1:34482”,“level”:“info”,“msg”:“Received request.“,”req_id”:2,“req_method”:“GET”,“req_path”:“/metrics”,“time”:“2023-06-26T11:50:45Z”}
                    {“client_addr”:“127.0.0.1:34482",“level”:“info”,“line”:“/authzConfig/systemPolicy.rego:8",“msg”:“Incoming request:  [\“metrics\“]”,“req_id”:2,“req_method”:“GET”,“req_path”:“/metrics”,“time”:“2023-06-26T11:50:45Z”}                                                   {“client_addr”:“127.0.0.1:34482",“level”:“info”,“line”:“/authzConfig/systemPolicy.rego:34",“msg”:“Request match metrics endpoint”,“req_id”:2,“req_method”:“GET”,“req_path”:“/metrics”,“time”:“2023-06-26T11:50:45Z”}                                                    {“client_addr”:“127.0.0.1:34482”,“level”:“info”,“msg”:“Sent response.“,”req_id”:2,“req_method”:“GET”,“req_path”:“/metrics”,“resp_bytes”:4371,“resp_duration”:1.945056,“resp_status”:200,“time”:“2023-06-26T11:50:45Z”}                                                  {“level”:“warning”,“msg”:“Distributed tracing: traces export: context deadline exceeded: rpc error: code = Unavailable desc = connection error: desc = \“transport: Error while dialing: dial tcp: address dummy_value: missing port in address\“”,“time”:“2023-06-26T11:50:47Z”}
                                   {“level”:“error”,“msg”:“Bundle load failed: request failed: error in response from OAuth2 token endpoint: “,”name”:“storagesvc”,“plugin”:“bundle”,“time”:“2023-06-26T11:50:51Z”}
{“level”:“warning”,“msg”:“Distributed tracing: traces export: context deadline exceeded: rpc error: code = Unavailable desc = connection error: desc = \“transport: Error while dialing: dial tcp: address dummy_value: missing port in address\“”,“time”:“2023-06-26T11:51:02Z”}
                                   {“level”:“error”,“msg”:“Bundle load failed: request failed: error in response from OAuth2 token endpoint: “,”name”:“storagesvc”,“plugin”:“bundle”,“time”:“2023-06-26T11:51:03Z”}
{“level”:“info”,“msg”:“Shutting down...“,”time”:“2

## Steps To Reproduce

Following is the configuration I have used : 

    plugins:
      envoy_ext_authz_grpc:
        addr: :9191
        path: istio/authz/allow
        dry-run: false
    decision_logs:
      console: true
    distributed_tracing:
      type: grpc
      service_name: authz-engine-opa
      address: dummy_value
    services:
      talip:
        url: http://storage-service.storage-service.cluster.local/v1/objects/a21a1909-c664-41be-bfc5-9a3ce0dae52c
        credentials:
          oauth2:
            client_id: some_client_id
            client_secret: some_client_secret
            token_url: https://somedomain.cluster.integration.pegaservice.net/uas/oauth/token
            additional_parameters:
              some_custom_key: some-custom-value
    bundles:
      storagesvc:
        service: talip
        resource: test1bundle.tar.gz

## Expected behavior

Oauth token should fetched properly and bundle fetching should work properly.

**Comment by srenatus** [comment] 2023-06-26 12:10
Closing the loop -- we've been discussing this briefly in Slack: https://openpolicyagent.slack.com/archives/CBR63TK2A/p1687779173014339

**Comment by anderseknert** [comment] 2023-06-26 13:50
Although surely annoying, this doesn't look like a bug in OPA to me. If the token server responds with anything but a 200 status code at the token endpoint, OPA will rightly fail and print the response body to the logs. In your case, it seems like the token server doesn't send back any errors in the body, which makes this rather awkward to debug, and most likely not compliant with the [OAuth2 spec](https://www.rfc-editor.org/rfc/rfc6749#section-5.2).

```go
if response.StatusCode != 200 {
    return nil, fmt.Errorf("error in response from OAuth2 token endpoint: %v", string(bodyRaw))
}
```

I suppose one improvement would be to at least log the status code, as that might give some clue as to what's up... but this looks like either a non-compliant server, or something wonky causing e.g. a 500 response or something like that.

**Comment by LionOnTheChase** [comment] 2023-06-26 15:28
After going through the code, I just figured out a workaround and token
generation is working fine with it.

*Workaround*:  I added client_id and client_secret under
additional_parameters and the oauth2 server started to give response.

It looks like a bug in the code
https://github.com/open-policy-agent/opa/blob/2ade22958acd028ef61178bf1cff9e5d223351b3/plugins/rest/auth.go#L360C2-L362C3

I don't have grant_type explicitly mentioned in my config. that could have
caused the clientid and clientsecret to be skipped from the request to
token_url.

Or, just the  r.SetBasicAuth(ap.ClientID, ap.ClientSecret) is not working
as expected.

And yes, improving the logging is also very desirable

**Comment by anderseknert** [comment] 2023-06-26 15:42
Using the basic authentication scheme for client authentication is not a bug, but following the OAuth2 [specification](https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1):

> The authorization server MUST support the HTTP Basic authentication scheme for authenticating clients that were issued a client password.

While using `additional_parameters` to provide the credentials might work, it's advised against:

>  Including the client credentials in the request-body using the two parameters is NOT RECOMMENDED and SHOULD be limited to clients unable to directly utilize the HTTP Basic authentication scheme

I would try to investigate why your server won't accept the credentials as required by the standard. 

If you'd like to improve the logging to include the status code, that would be a welcome contribution!

**Comment by ashutosh-narkar** [comment] 2023-06-26 18:47
Can we close this as it doesn't seem to be a bug in OPA and possibly a server implementation issue.

**Comment by anderseknert** [comment] 2023-06-26 21:12
Sounds reasonable to me, so I'll close for the time being, and we can re-open if there's evidence of an actual bug here.

@LionOnTheChase that doesn't mean I'm off the case. Let's work together to try and find out why you're seeing this.

**Closed by anderseknert** 2023-06-26 21:12 UTC
Labels: bug
