### ISSUE TITLE
json.match_schema() does not validate regex patterns defined in the schema

### ISSUE THREAD

**Issue by mscudlik** [open-policy-agent/opa#6614] opened 2024-03-06 09:10 UTC
## Short description 

json.match_schema() does not validate regex patterns defined in the schema

## Steps To Reproduce

I have created a small example:
https://github.com/mscudlik/opa-json-match-schema

## Expected behavior

In my example, the command 
```shell
opa eval -b . -f pretty data.string_regex_pattern.policy --input string_regex_pattern/input/invalid_regex/data.json
```
should fail, and the test
https://github.com/mscudlik/opa-json-match-schema/blob/main/string_regex_pattern/test/string_regex_pattern_test.rego#L23

Should work as expected, because `bar %%% !` does not match `^[a-zA-Z0-9_-]+$`

## Additional context

Usecase is to validate the input (which i cannot trust)

## opa version

```shell
Version: 0.62.0
Build Commit: 1d0ab93822e83a4165c78372a7fb4c05e14a8bca
Build Timestamp: 2024-02-29T17:07:11Z
Build Hostname: Mac-1709226273754.local
Go Version: go1.22.0
Platform: darwin/amd64
WebAssembly: available
```

**Comment by jonvance** [comment] 2024-04-23 20:02
I see the following in the [parseSchema()](https://github.com/open-policy-agent/opa/blob/main/internal/gojsonschema/schema.go#L519-L522) function: 

```
// NOTE: Regex compilation step removed as we don't use "pattern" attribute for
// type checking, and this would cause schemas to fail if they included patterns
// that were valid ECMA regex dialect but not known to Go (i.e. the regexp.Compile
// function), such as patterns with negative lookahead
```

Are there known black listed patterns that could not be captured? I'm wondering if we could write an exclusionary set so that we do not throw out false positives in regex captures, but we can still capture certain regex patterns.

**Comment by anderseknert** [comment] 2024-04-23 21:25
I hadn't seen this before, but this looks like a duplicate of #6089, where some background to this issue is provided. Let's continue the discussion there.

**Closed by anderseknert** 2024-04-23 21:25 UTC
Labels: bug

**Comment by srenatus** [comment] 2024-07-04 11:35
Duplicate
