### ISSUE TITLE
opa build `--ignore` fails to work with `-b` flag

### ISSUE THREAD

**Issue by aflmp** [open-policy-agent/opa#2944] opened 2020-11-24 20:53 UTC
## Expected Behavior
running `opa build -b ./policies --ignore="*_test.rego" -o my-policies.tar.gz`
should produce a bundle with rego files (not including *_test.rego) along with correct `.manifest`.

## Actual Behavior
`opa build -b ./policies --ignore="*_test.rego" -o my-policies.tar.gz`
`--ignore` flag is not respected with `-b`, test rego files will be included in the bundle.

`opa build ./policies --ignore="*_test.rego" -o my-policies.tar.gz`
this works fine, but `.manifest` is not reflected correctly in the bundle.

## Steps to Reproduce the Problem
below is a sample setup
```rego
/tmp/issue
❯ tree -a .
.
└── policies
    ├── .manifest
    ├── first.rego
    └── first_test.rego

1 directory, 3 files

/tmp/issue
❯ cat policies/first.rego
package one

allow {
        input.hello == "world"
}

/tmp/issue
❯ cat policies/first_test.rego
package one

test_allow {
        allow with input as {
                "hello": "world"
        }
}

test_not_allow {
        not allow with input as {
                "hello": "bye"
        }
}

/tmp/issue
❯ cat ./policies/.manifest
{"revision": "", "roots": ["one"]}
```
building the bundle
```
/tmp/issue
❯ cat ./policies/.manifest

/tmp/issue
❯ opa build -b ./policies --ignore="*_test.rego" -o my-bundle.tar.gz // --ignore not being respected

/tmp/issue
❯ tar -tvf my-bundle.tar.gz
-rw-------  0 0      0           3 Dec 31  1969 /data.json
-rw-------  0 0      0          47 Dec 31  1969 /policies/first.rego
-rw-------  0 0      0         130 Dec 31  1969 /policies/first_test.rego
-rw-------  0 0      0          32 Dec 31  1969 /.manifest
```

Without `-b` flag, the test rego files are ignored but the default .manifest shows up
```
/tmp/issue
❯ opa build ./policies --ignore="*_test.rego" -o my-bundle.tar.gz

/tmp/issue
❯ tar -tvf my-bundle.tar.gz
-rw-------  0 0      0           3 Dec 31  1969 /data.json
-rw-------  0 0      0          47 Dec 31  1969 /policies/first.rego
-rw-------  0 0      0          29 Dec 31  1969 /.manifest

/tmp/issue
❯ tar -zxvf my-bundle.tar.gz /.manifest
tar: Removing leading '/' from member names
x .manifest

/tmp/issue
❯ cat .manifest
{"revision":"","roots":[""]}
```

## Additional Info
```
❯ opa version
Version: 0.24.0
Build Commit: b69b80b
Build Timestamp: 2020-10-13T21:36:15Z
Build Hostname: ffabd2c9ce42
Go Version: go1.14.9
```

**Comment by anderseknert** [comment] 2022-01-09 19:09
@olamiko will give this one a shot! Mentioning here since it seems impossible to assign unless someone has "interacted" with the issue in some way. I'm hoping this will be enough.

**Comment by olamiko** [comment] 2022-01-10 12:34
@anderseknert, interacting with this now :)

**Comment by olamiko** [comment] 2022-01-10 13:18
# Quick tests 
* I tried to reproduce the bug above and I found that:
  * the `opa build` command doesn't ignore the files when the flag `-b` is used.
  * no manifest file is generated when the command  `opa build ./policies --ignore="*_test.rego" -o my-bundle.tar.gz` is run. However, the original author mentioned that a default manifest is added.

**Comment by anderseknert** [comment] 2022-01-10 18:41
That's just a difference in how the command works with and wthout the `--bundle` flag. Not one I'm particularly fond of, but it's what it is. `--ignore` not working in combination with `--bundle` is a real bug though.

**Comment by olamiko** [comment] 2022-01-12 10:36
Thanks @anderseknert, I found the bug. However, before I fix it, I will write a test (that will surely fail) and once I have confirmed the behaviour with a test, I will fix it.

**Comment by redak-hash** [comment] 2022-02-17 18:36
hello, any updates ?

**Comment by olamiko** [comment] 2022-02-17 18:39
Hi @redak-hash, I am almost done. I took a break some days ago

**Comment by olamiko** [comment] 2022-04-29 11:53
With regards to this issue, the solution is straightforward. 

However, the solution (adding a `filter` to the bundle creation process) breaks many tests because of the nature of the filter used internally in OPA. (check the closed pull request).

I could not figure a way to solve this problem without requiring a major rewrite of all the tests in the package

**Comment by ashutosh-narkar** [comment] 2022-09-01 15:35
Fixed in https://github.com/open-policy-agent/opa/pull/5044

**Closed by ashutosh-narkar** 2022-09-01 15:35 UTC
Labels: bug, usability, distribution
