### ISSUE TITLE
Support envoy plugin with discvoery

### ISSUE THREAD

**Issue by omerlh** [open-policy-agent/opa#1946] opened 2019-12-06 09:12 UTC
# Expected Behavior
Being able to use both discovery and the istio plugin

# Actual Behavior
Not working. When trying to enable the plugin using discovery like the following:
```rego
package discovery

config = {
  "bundles": {
    "common": {
      "service": "service-registry",
      "resource": "bundles/common.tar.gz"
    },
    "web-api": {
      "service": "service-registry",
      "resource": bundle_name
    }
  },
  "decision_logs": {
    "console": true
  },
  "plugins": {
    "envoy_ext_authz_grpc": {
      "addr": ":9191",
      "query": "data.envoy.authz.allow"
    }
  }
}

bundle_name = sprintf("bundles/%s.tar.gz", [runtime_config.labels.app])
```
The plugin is not enabled. When trying to enable it using config file, it also not enabled. When trying to enable it using command like (using `--set`), I'm getting an error:
```
 plugins cannot be specified in the bootstrap configuration when discovery enabled
```

# Steps to Reproduce the Problem

  1. Enable discovery in config
  2. Try to enable istio plugin

# Additional Info
Using opa with tag `openpolicyagent/opa:latest-istio`

**Comment by tsandall** [comment] 2019-12-09 16:48
Like bundles and other components, plugins can't be configured in the bootstrap config when discovery is enabled because it opens a can of worms (e.g., which config should take precedent?)

You _should_ be able to enable the ext authz plugin inside the discovered config though. I just tried this out and confirmed that the server is started (admittedly, I only looked at the logs and verified the process was listening on the expected port.)

```
./opa_istio_linux_amd64 run -s -c ~/temp/data.json.1 --set=services.test.url=https://some.domain.com/v1 --set=services.test.credentials.bearer.token=TOKEN
{"addrs":[":8181"],"insecure_addr":"","level":"info","msg":"Initializing server.","time":"2019-12-09T11:45:19-05:00"}
{"level":"info","msg":"Starting bundle downloader.","name":"systems/c55f3d08fbb44a78936ed9ca57feb0a3?no_data=systems","plugin":"bundle","time":"2019-12-09T11:45:19-05:00"}
{"level":"info","msg":"Starting decision logger.","plugin":"decision_logs","time":"2019-12-09T11:45:19-05:00"}
{"level":"info","msg":"Starting status reporter.","plugin":"status","time":"2019-12-09T11:45:19-05:00"}
{"level":"info","msg":"Log upload skipped.","plugin":"decision_logs","time":"2019-12-09T11:45:19-05:00"}
{"addr":"127.0.0.1:9191","dry-run":false,"enable-reflection":false,"level":"info","msg":"Starting gRPC server.","query":"data.rules.allow_envoy","time":"2019-12-09T11:45:19-05:00"}
{"level":"info","msg":"Bundle downloaded and activated successfully. Etag updated to \"738b8455a32c440aed337b87e85bc38daa72b1c478c56aa6ce1c367f4471fe6d\".","name":"systems/c55f3d08fbb44a78936ed9ca57feb0a3?no_data=systems","plugin":"bundle","time":"2019-12-09T11:45:20-05:00"}
{"level":"info","msg":"Status update sent successfully in response to bundle update.","plugin":"status","time":"2019-12-09T11:45:20-05:00"}
```

Here is the corresponding config file:

```
{
  "bundle": {
    "name": "systems/c55f3d08fbb44a78936ed9ca57feb0a3?no_data=systems",
    "polling": {
      "max_delay_seconds": 15,
      "min_delay_seconds": 10
    },
    "service": "test"
  },
  "decision_logs": {
    "reporting": {
      "max_delay_seconds": 15,
      "min_delay_seconds": 10,
      "upload_size_limit_bytes": 131072
    },
    "service": "test"
  },
  "default_decision": "rules/allow_envoy",
  "plugins": {
    "envoy_ext_authz_grpc": {
      "addr": "127.0.0.1:9191",
      "dry-run": false,
      "query": "data.rules.allow_envoy"
    }
  },
  "status": {
    "service": "test"
  }
}
```

Can you share more details to help reproduce this problem?

**Comment by tsandall** [comment] 2019-12-16 22:17
Closing since it's possible to configure the plugin via discovery today and adding support for mixing discovered and non-discovered config is out-of-scope. Feel free to re-open if needed.

**Closed by tsandall** 2019-12-16 22:17 UTC

**Comment by omerlh** [comment] 2019-12-17 12:58
Sorry for the late response, I think I had another issue. I can confirm it's working.
