### ISSUE TITLE
No rootles image despite the note in the release 0.58

### ISSUE THREAD

**Issue by sabinahofmann** [open-policy-agent/opa#6394] opened 2023-11-08 12:31 UTC
## Short description 
Based on this note [v.58.0](https://github.com/open-policy-agent/opa/releases/tag/v0.58.0), it is expected that all images from 0.58 will run rootless. Reference is also made to the release in the corresponding variants [v0.58.0-envoy](https://github.com/open-policy-agent/opa-envoy-plugin/releases/tag/v0.58.0-envoy). 

According to the release note, I should not get an warning if I run an rootless image, because it's enought if the uid is not 0.

Examples:

* OPA Envoy Plugin 0.58.0
** Image Layer: https://hub.docker.com/layers/openpolicyagent/opa/0.58.0-envoy/images/sha256-f53e69eeee948b1d725877751720864221f6353e515211d54455f08b5abad671?context=explore
* OPA Envoy Plugin 0.58.0 rootless
** Image Layser: https://hub.docker.com/layers/openpolicyagent/opa/0.58.0-envoy-rootless/images/sha256-06418ed931f8f125e0ff8c235c88a2a3bdaad61002ecfe598ff3554f4dc7fe19?context=explore

## Steps To Reproduce
- Have a look at the Image Layers of OPA Envoy Plugin 0.58.0 rootless & OPA Envoy Plugin 0.58.0
- Run the image 0.58.0-envoy-rootless and take a look into the logs. You will get a warning `"OPA running with uid or gid 0. Running OPA with root privileges is not recommended."`(see below https://github.com/open-policy-agent/opa/blob/30a244e580f77ecf30a6b27111cec4a064809652/runtime/check_user_unix.go#L22)

## Expected behavior
Based on the note, I expect all variants images of OPA to run rootless. Both the UID and the GID and not onlay UID should be not 0 according to the text in release notes. Also the warning should be more should be more accurate. It's enough to set only UID not to 0.

**Comment by anderseknert** [comment] 2023-11-08 13:12
Hi @sabinahofmann 👋 And thanks for reporting this. I'm unable to reproduce it here, I think. Trying to run both of the versions I'm only seeing the UID warning when using the non-rootless version. Starting from the next version, this will be the default behavior. Am I missing something obvious? 😃 

```shell
docker run openpolicyagent/opa:0.58.0-envoy-rootless run --server
```
```shell
'WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{"addrs":[":8181"],"diagnostic-addrs":[],"level":"info","msg":"Initializing server. OPA is running on a public (0.0.0.0) network interface. Unless you intend to expose OPA outside of the host, binding to the localhost interface (--addr localhost:8181) is recommended. See https://www.openpolicyagent.org/docs/latest/security/#interface-binding","time":"2023-11-08T13:09:07Z"}
```

```shell
docker run openpolicyagent/opa:0.58.0-envoy run --server
```
```shell
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{"addrs":[":8181"],"diagnostic-addrs":[],"level":"info","msg":"Initializing server. OPA is running on a public (0.0.0.0) network interface. Unless you intend to expose OPA outside of the host, binding to the localhost interface (--addr localhost:8181) is recommended. See https://www.openpolicyagent.org/docs/latest/security/#interface-binding","time":"2023-11-08T13:09:36Z"}
{"level":"warning","msg":"OPA running with uid or gid 0. Running OPA with root privileges is not recommended.","time":"2023-11-08T13:09:36Z"}
```

**Comment by ashutosh-narkar** [comment] 2023-11-08 17:18
Just to clarify, we plan to stop publishing the `rootless` variant for the OPA images. The OPA-Envoy plugin still has the `rootless` variant for now and we will deprecate that as well.

**Comment by anderseknert** [comment] 2023-11-09 16:17
Yeah, looks like the makefile [only sets the UID](https://github.com/open-policy-agent/opa-envoy-plugin/blob/main/Makefile#L105) and not the GID.

That differs from the OPA one, where we [set both](https://github.com/open-policy-agent/opa/blob/main/Dockerfile#L15). We should have that corrected, I think. Would you want to submit a fix for that?

**Comment by sabinahofmann** [comment] 2023-11-09 16:25
Yeah, I can do it.

**Comment by sabinahofmann** [comment] 2023-11-12 10:22
Could somebody please review the PR. Thank you!

**Comment by ashutosh-narkar** [comment] 2023-11-13 16:32
Merged. Thanks @sabinahofmann!

**Closed by ashutosh-narkar** 2023-11-13 16:32 UTC
Labels: question

**Comment by ashutosh-narkar** [comment] 2023-11-30 23:23
Not atm but we can look into that for a future release.
