### ISSUE TITLE
/bin/sh: ./opa: not found in Docker when upgrading to v0.29.4

### ISSUE THREAD

**Issue by ZachMayry** [open-policy-agent/opa#3532] opened 2021-06-04 15:54 UTC
## Expected Behavior
OPA server runs

## Actual Behavior
`/bin/sh: ./opa: not found`

## Steps to Reproduce the Problem
dockerfile
```dockerfile
FROM node:fermium-alpine
RUN apk update
COPY ./opa /opa
WORKDIR /
EXPOSE 8181
RUN ./opa run --server
```
1. download opa `curl -L -o opa https://www.openpolicyagent.org/downloads/latest/opa_linux_amd64/; chmod +x ./opa`
2. copy dockerfile to a file named `Dockerfile`
3. `docker build .`

## OPA Environment

OPA Version: 0.28.0 - works just fine
OPA Version: 0.29.4 - does not run

Exact Error message
```
 => ERROR [4/5] RUN ./opa run --server                                                                0.4s
------                                                                                                     
 > [4/5] RUN ./opa run --server:
#8 0.383 /bin/sh: ./opa: not found
------
executor failed running [/bin/sh -c ./opa run --server]: exit code: 127
```

## Additional Info

0.29.4 works just fine on a Mac, just not on Linux via docker. Could be related to the image we are using but that is our standard image as all of our services run on node. We use yarn workspaces to standardize how we run our services.

**Comment by tsandall** [comment] 2021-06-04 16:05
@ZachMayry thanks for filing this...

Can you try the same except curl for the static executable: `https://www.openpolicyagent.org/downloads/latest/opa_linux_amd64_static`

Some recent changes related to wasm support in OPA necessitate libc dependencies (which aren't available in alpine). You probably don't care about wasm support for now so just use the static executable.

Assuming this fixes it, I'll send out a post on Slack and update the release notes to be more obvious about this.

Sorry for the inconvenience!

**Comment by ZachMayry** [comment] 2021-06-04 16:11
That works!

**Comment by tsandall** [comment] 2021-06-04 16:17
Yes, the static version will be supported (and it won't magically become dynamic at some point like the other linux executable did 😅 )

**Comment by ZachMayry** [comment] 2021-06-04 16:23
What do you mean by "dynamic"?

**Comment by tsandall** [comment] 2021-06-04 16:34
It won't gain any dynamic library dependencies. The `opa_linux_amd64_static` is statically linked, i.e., you can it on _any_ linux/amd64 systems as it has no system library dependencies (even libc is not needed...)

**Comment by tsandall** [comment] 2021-06-04 16:54
Closing because this is a dupe of #3499

**Closed by tsandall** 2021-06-04 16:54 UTC
