### ISSUE TITLE
Fix bundle etag caching

### ISSUE THREAD

**Issue by kubaj** [open-policy-agent/opa#1928] opened 2019-11-27 10:05 UTC
# Expected Behavior
A bundle is downloaded, Etag header's value is stored if present. On the second request, Etag is provided in the `If-None-Match` header and the server returns 304 response. If this response doesn't contain `Etag` header, previous Etag value should be used in the next response.

# Actual Behavior
A bundle is downloaded with every other request when the server doesn't return the Etag header in a 304 response. This causes increased latency of the OPA and high CPU usage if the bundle has a larger size. 

# Additional Info
Version: OPA Istio plugin 0.14.2
Server that stores bundles: Google Cloud Storage

Example config:
```
plugins:
  envoy_ext_authz_grpc:
    addr: :9191
    query: data.authz.allow

services:
  - name: gcs
    url: https://storage.googleapis.com/some-random-bucket

bundles:
  authz:
    service: gcs
    resource: bundle.tar.gz
    polling:
      min_delay_seconds: 5
      max_delay_seconds: 10
```

Logs:
```
{"addrs":[":8181"],"insecure_addr":"","level":"info","msg":"Initializing server.","time":"2019-11-27T10:02:32Z"}
{"level":"info","msg":"Starting bundle downloader.","name":"authz","plugin":"bundle","time":"2019-11-27T10:02:35Z"}
{"addr":":9191","dry-run":false,"enable-reflection":false,"level":"info","msg":"Starting gRPC server.","query":"data.authz.allow","time":"2019-11-27T10:02:35Z"}
{"level":"info","msg":"Bundle downloaded and activated successfully. Etag updated to \"6d0c17be691a1846f753b423cb17d0bf\".","name":"authz","plugin":"bundle","time":"2019-11-27T10:02:38Z"}
{"level":"info","msg":"Bundle downloaded and activated successfully. Etag updated to \"6d0c17be691a1846f753b423cb17d0bf\".","name":"authz","plugin":"bundle","time":"2019-11-27T10:02:54Z"}
{"level":"info","msg":"Bundle downloaded and activated successfully. Etag updated to \"6d0c17be691a1846f753b423cb17d0bf\".","name":"authz","plugin":"bundle","time":"2019-11-27T10:03:10Z"}
{"level":"info","msg":"Bundle downloaded and activated successfully. Etag updated to \"6d0c17be691a1846f753b423cb17d0bf\".","name":"authz","plugin":"bundle","time":"2019-11-27T10:03:21Z"}
{"level":"info","msg":"Bundle downloaded and activated successfully. Etag updated to \"6d0c17be691a1846f753b423cb17d0bf\".","name":"authz","plugin":"bundle","time":"2019-11-27T10:03:34Z"}
```

**Comment by patrick-east** [comment] 2019-12-02 22:10
Thanks for sharing! One more request, can you provide debug logs too?

Looking into this more I can't repro this with OPA normally. I'm wondering if there is something happening with the istio/envoy integration that is messing with the responses. Debug logs should help as we can see all of the data (please be sure to redact any sensitive info!!).

For example with the latest OPA:
```
{14:05} ~/p/g/s/g/o/opa:master ✓ ❯ opa run \
    -s \
    -l debug \
    --log-format json-pretty \
    --set services.gcs.url=https://storage.googleapis.com \
    --set bundles.b1.service=gcs \
    --set bundles.b1.resource=/opa-bundles/b1.tar.gz \
    --set bundles.b1.polling.max_delay_seconds=5 \
    --set bundles.b1.polling.min_delay_seconds=5
{
  "addrs": [
    ":8181"
  ],
  "insecure_addr": "",
  "level": "info",
  "msg": "Initializing server.",
  "time": "2019-12-02T14:05:42-08:00"
}
{
  "level": "info",
  "msg": "Starting bundle downloader.",
  "name": "b1",
  "plugin": "bundle",
  "time": "2019-12-02T14:05:42-08:00"
}
{
  "level": "debug",
  "msg": "Download starting.",
  "time": "2019-12-02T14:05:42-08:00"
}
{
  "headers": {
    "User-Agent": [
      "Open Policy Agent/ (darwin, amd64)"
    ]
  },
  "level": "debug",
  "method": "GET",
  "msg": "Sending request.",
  "time": "2019-12-02T14:05:42-08:00",
  "url": "https://storage.googleapis.com/opa-bundles/b1.tar.gz"
}
{
  "headers": {
    "Accept-Ranges": [
      "bytes"
    ],
    "Age": [
      "476"
    ],
    "Alt-Svc": [
      "quic=\":443\"; ma=2592000; v=\"46,43\",h3-Q050=\":443\"; ma=2592000,h3-Q049=\":443\"; ma=2592000,h3-Q048=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000"
    ],
    "Cache-Control": [
      "public, max-age=3600"
    ],
    "Content-Length": [
      "425"
    ],
    "Content-Type": [
      "application/x-gzip"
    ],
    "Date": [
      "Mon, 02 Dec 2019 21:57:46 GMT"
    ],
    "Etag": [
      "\"61f6cf0de9907870c7b1fbc97766a1d3\""
    ],
    "Expires": [
      "Mon, 02 Dec 2019 22:57:46 GMT"
    ],
    "Last-Modified": [
      "Mon, 02 Dec 2019 21:48:54 GMT"
    ],
    "Server": [
      "UploadServer"
    ],
    "X-Goog-Generation": [
      "1575323334821453"
    ],
    "X-Goog-Hash": [
      "crc32c=w3PKFQ==",
      "md5=YfbPDemQeHDHsfvJd2ah0w=="
    ],
    "X-Goog-Metageneration": [
      "2"
    ],
    "X-Goog-Storage-Class": [
      "STANDARD"
    ],
    "X-Goog-Stored-Content-Encoding": [
      "identity"
    ],
    "X-Goog-Stored-Content-Length": [
      "425"
    ],
    "X-Guploader-Uploadid": [
      "AEnB2Uqw55Ry2w1-NWfSSj4P7eqMdBzSr8hnLXy_eEtFfAWLAbi9Z0RbVfoUQEEKq-3rj3GVvJG1IoPWe1u7bR94tnW4oC41w4DyIFPorRCIUeJ6hix0Xq0"
    ]
  },
  "level": "debug",
  "method": "GET",
  "msg": "Received response.",
  "status": "200 OK",
  "time": "2019-12-02T14:05:42-08:00",
  "url": "https://storage.googleapis.com/opa-bundles/b1.tar.gz"
}
{
  "level": "debug",
  "msg": "Download in progress.",
  "time": "2019-12-02T14:05:42-08:00"
}
{
  "level": "debug",
  "msg": "Bundle activation in progress. Opening storage transaction.",
  "name": "b1",
  "plugin": "bundle",
  "time": "2019-12-02T14:05:42-08:00"
}
{
  "level": "debug",
  "msg": "Opened storage transaction (5).",
  "name": "b1",
  "plugin": "bundle",
  "time": "2019-12-02T14:05:42-08:00"
}
{
  "level": "debug",
  "msg": "Closing storage transaction (5).",
  "name": "b1",
  "plugin": "bundle",
  "time": "2019-12-02T14:05:42-08:00"
}
{
  "level": "info",
  "msg": "Bundle downloaded and activated successfully. Etag updated to \"61f6cf0de9907870c7b1fbc97766a1d3\".",
  "name": "b1",
  "plugin": "bundle",
  "time": "2019-12-02T14:05:42-08:00"
}
{
  "level": "debug",
  "msg": "Waiting 5s before next download/retry.",
  "time": "2019-12-02T14:05:42-08:00"
}
{
  "level": "debug",
  "msg": "Download starting.",
  "time": "2019-12-02T14:05:47-08:00"
}
{
  "headers": {
    "If-None-Match": [
      "\"61f6cf0de9907870c7b1fbc97766a1d3\""
    ],
    "User-Agent": [
      "Open Policy Agent/ (darwin, amd64)"
    ]
  },
  "level": "debug",
  "method": "GET",
  "msg": "Sending request.",
  "time": "2019-12-02T14:05:47-08:00",
  "url": "https://storage.googleapis.com/opa-bundles/b1.tar.gz"
}
{
  "headers": {
    "Age": [
      "481"
    ],
    "Alt-Svc": [
      "quic=\":443\"; ma=2592000; v=\"46,43\",h3-Q050=\":443\"; ma=2592000,h3-Q049=\":443\"; ma=2592000,h3-Q048=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000"
    ],
    "Date": [
      "Mon, 02 Dec 2019 21:57:46 GMT"
    ],
    "Etag": [
      "\"61f6cf0de9907870c7b1fbc97766a1d3\""
    ],
    "Expires": [
      "Mon, 02 Dec 2019 22:57:46 GMT"
    ]
  },
  "level": "debug",
  "method": "GET",
  "msg": "Received response.",
  "status": "304 Not Modified",
  "time": "2019-12-02T14:05:47-08:00",
  "url": "https://storage.googleapis.com/opa-bundles/b1.tar.gz"
}
{
  "level": "debug",
  "msg": "Bundle download skipped, server replied with not modified.",
  "name": "b1",
  "plugin": "bundle",
  "time": "2019-12-02T14:05:47-08:00"
}
{
  "level": "debug",
  "msg": "Waiting 5s before next download/retry.",
  "time": "2019-12-02T14:05:47-08:00"
}
```

Everything is working as expected (and that bucket is public, anyone else feel free to use it to try this out.. I'll leave it up for a while).

**Comment by patrick-east** [comment] 2019-12-06 00:16
Quick update, I tested this out with the v0.14.2 opa-istio-plugin binary and everything works fine running it by itself.

This leads me to believe that the issue is likely with the environment where it is running. Debug logs on the system it reproduces in along with more details about the config would help (eg. using envoy+istio? any special handling for http requests in/out of OPA?)

**Comment by kubaj** [comment] 2019-12-06 09:58
Hi @patrick-east , here are the debug logs.

```
{
    "addrs": [
        ":8181"
    ],
    "insecure_addr": "",
    "level": "info",
    "msg": "Initializing server.",
    "time": "2019-12-06T09:48:41Z"
}
{
    "level": "info",
    "msg": "Starting bundle downloader.",
    "name": "authz",
    "plugin": "bundle",
    "time": "2019-12-06T09:48:43Z"
}
{
    "level": "debug",
    "msg": "Download starting.",
    "time": "2019-12-06T09:48:43Z"
}
{
    "headers": {
        "User-Agent": [
            "Open Policy Agent/0.14.2 (linux, amd64)"
        ]
    },
    "level": "debug",
    "method": "GET",
    "msg": "Sending request.",
    "time": "2019-12-06T09:48:43Z",
    "url": "https://storage.googleapis.com/[redacted]/bundle.tar.gz"
}
{
    "headers": {
        "Accept-Ranges": [
            "bytes"
        ],
        "Alt-Svc": [
            "quic=\":443\"; ma=2592000; v=\"46,43\",h3-Q050=\":443\"; ma=2592000,h3-Q049=\":443\"; ma=2592000,h3-Q048=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000"
        ],
        "Cache-Control": [
            "no-cache,max-age=0"
        ],
        "Content-Length": [
            "2754"
        ],
        "Content-Type": [
            "application/x-gzip"
        ],
        "Date": [
            "Fri, 06 Dec 2019 09:48:44 GMT"
        ],
        "Etag": [
            "\"e2f6d8eb2978e2567f6cb434e7344bbc\""
        ],
        "Expires": [
            "Fri, 06 Dec 2019 09:48:44 GMT"
        ],
        "Last-Modified": [
            "Wed, 04 Dec 2019 11:24:50 GMT"
        ],
        "Server": [
            "UploadServer"
        ],
        "X-Goog-Generation": [
            "1575458690944869"
        ],
        "X-Goog-Hash": [
            "crc32c=nHYxIQ==",
            "md5=4vbY6yl44lZ/bLQ05zRLvA=="
        ],
        "X-Goog-Metageneration": [
            "3"
        ],
        "X-Goog-Storage-Class": [
            "STANDARD"
        ],
        "X-Goog-Stored-Content-Encoding": [
            "identity"
        ],
        "X-Goog-Stored-Content-Length": [
            "2754"
        ],
        "X-Guploader-Uploadid": [
            "AEnB2UqL7M4zf9DG2qIzFBDT8BRh3eWOJnCAZA1Aw3wGjQHYBkRNkaTFhWfU708JWlZI-IOHIPxjQW-_eaFpUOcohLo2KSvJ3A"
        ]
    },
    "level": "debug",
    "method": "GET",
    "msg": "Received response.",
    "status": "200 OK",
    "time": "2019-12-06T09:48:44Z",
    "url": "https://storage.googleapis.com/[redacted]/bundle.tar.gz"
}
{
    "level": "debug",
    "msg": "Download in progress.",
    "time": "2019-12-06T09:48:44Z"
}
{
    "level": "debug",
    "msg": "Bundle activation in progress. Opening storage transaction.",
    "name": "authz",
    "plugin": "bundle",
    "time": "2019-12-06T09:48:44Z"
}
{
    "level": "debug",
    "msg": "Opened storage transaction (5).",
    "name": "authz",
    "plugin": "bundle",
    "time": "2019-12-06T09:48:44Z"
}
{
    "level": "debug",
    "msg": "Closing storage transaction (5).",
    "name": "authz",
    "plugin": "bundle",
    "time": "2019-12-06T09:48:47Z"
}
{
    "level": "info",
    "msg": "Bundle downloaded and activated successfully. Etag updated to \"e2f6d8eb2978e2567f6cb434e7344bbc\".",
    "name": "authz",
    "plugin": "bundle",
    "time": "2019-12-06T09:48:47Z"
}
{
    "level": "debug",
    "msg": "Waiting 8.322800266s before next download/retry.",
    "time": "2019-12-06T09:48:47Z"
}
{
    "level": "debug",
    "msg": "Download starting.",
    "time": "2019-12-06T09:48:55Z"
}
{
    "headers": {
        "If-None-Match": [
            "\"e2f6d8eb2978e2567f6cb434e7344bbc\""
        ],
        "User-Agent": [
            "Open Policy Agent/0.14.2 (linux, amd64)"
        ]
    },
    "level": "debug",
    "method": "GET",
    "msg": "Sending request.",
    "time": "2019-12-06T09:48:55Z",
    "url": "https://storage.googleapis.com/[redacted]/bundle.tar.gz"
}
{
    "headers": {
        "Alt-Svc": [
            "quic=\":443\"; ma=2592000; v=\"46,43\",h3-Q050=\":443\"; ma=2592000,h3-Q049=\":443\"; ma=2592000,h3-Q048=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000"
        ],
        "Cache-Control": [
            "no-cache,max-age=0"
        ],
        "Content-Length": [
            "0"
        ],
        "Date": [
            "Fri, 06 Dec 2019 09:48:55 GMT"
        ],
        "Expires": [
            "Fri, 06 Dec 2019 09:48:55 GMT"
        ],
        "Last-Modified": [
            "Wed, 04 Dec 2019 11:24:50 GMT"
        ],
        "Server": [
            "UploadServer"
        ],
        "X-Guploader-Uploadid": [
            "AEnB2UpWe2LtMIAkgq37nkK6UAgMTHsEX4hXNDRJ41svTKVqvKMUc1TnuoB1n1SlLYje_E9GzfPnf37lS2QRJqYgiBJ7Jxd5kQ"
        ]
    },
    "level": "debug",
    "method": "GET",
    "msg": "Received response.",
    "status": "304 Not Modified",
    "time": "2019-12-06T09:48:55Z",
    "url": "https://storage.googleapis.com/[redacted]/bundle.tar.gz"
}
{
    "level": "debug",
    "msg": "Waiting 7.188570935s before next download/retry.",
    "time": "2019-12-06T09:48:55Z"
}
{
    "level": "debug",
    "msg": "Download starting.",
    "time": "2019-12-06T09:49:02Z"
}
{
    "headers": {
        "User-Agent": [
            "Open Policy Agent/0.14.2 (linux, amd64)"
        ]
    },
    "level": "debug",
    "method": "GET",
    "msg": "Sending request.",
    "time": "2019-12-06T09:49:02Z",
    "url": "https://storage.googleapis.com/[redacted]/bundle.tar.gz"
}
{
    "headers": {
        "Accept-Ranges": [
            "bytes"
        ],
        "Alt-Svc": [
            "quic=\":443\"; ma=2592000; v=\"46,43\",h3-Q050=\":443\"; ma=2592000,h3-Q049=\":443\"; ma=2592000,h3-Q048=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000"
        ],
        "Cache-Control": [
            "no-cache,max-age=0"
        ],
        "Content-Length": [
            "2754"
        ],
        "Content-Type": [
            "application/x-gzip"
        ],
        "Date": [
            "Fri, 06 Dec 2019 09:49:02 GMT"
        ],
        "Etag": [
            "\"e2f6d8eb2978e2567f6cb434e7344bbc\""
        ],
        "Expires": [
            "Fri, 06 Dec 2019 09:49:02 GMT"
        ],
        "Last-Modified": [
            "Wed, 04 Dec 2019 11:24:50 GMT"
        ],
        "Server": [
            "UploadServer"
        ],
        "X-Goog-Generation": [
            "1575458690944869"
        ],
        "X-Goog-Hash": [
            "crc32c=nHYxIQ==",
            "md5=4vbY6yl44lZ/bLQ05zRLvA=="
        ],
        "X-Goog-Metageneration": [
            "3"
        ],
        "X-Goog-Storage-Class": [
            "STANDARD"
        ],
        "X-Goog-Stored-Content-Encoding": [
            "identity"
        ],
        "X-Goog-Stored-Content-Length": [
            "2754"
        ],
        "X-Guploader-Uploadid": [
            "AEnB2Uo0L-2IagAbTjpXnHQS-A8vougd7ye69nDVSpkttw6GbZ_XZJ2fQ5hqCsqWm5syTXD0uzbUqcoy-S7AbREBmfPHCKfWfg"
        ]
    },
    "level": "debug",
    "method": "GET",
    "msg": "Received response.",
    "status": "200 OK",
    "time": "2019-12-06T09:49:02Z",
    "url": "https://storage.googleapis.com/[redacted]/bundle.tar.gz"
}
{
    "level": "debug",
    "msg": "Download in progress.",
    "time": "2019-12-06T09:49:02Z"
}
{
    "level": "debug",
    "msg": "Bundle activation in progress. Opening storage transaction.",
    "name": "authz",
    "plugin": "bundle",
    "time": "2019-12-06T09:49:03Z"
}
{
    "level": "debug",
    "msg": "Opened storage transaction (6).",
    "name": "authz",
    "plugin": "bundle",
    "time": "2019-12-06T09:49:03Z"
}
{
    "level": "debug",
    "msg": "Closing storage transaction (6).",
    "name": "authz",
    "plugin": "bundle",
    "time": "2019-12-06T09:49:03Z"
}
{
    "level": "info",
    "msg": "Bundle downloaded and activated successfully. Etag updated to \"e2f6d8eb2978e2567f6cb434e7344bbc\".",
    "name": "authz",
    "plugin": "bundle",
    "time": "2019-12-06T09:49:03Z"
}
{
    "level": "debug",
    "msg": "Waiting 7.123187485s before next download/retry.",
    "time": "2019-12-06T09:49:03Z"
}
```

I've run this in the Docker, image `openpolicyagent/opa:0.14.2`. I've mounted the following config into the container:
```
services:
  - name: gcs
    url: https://storage.googleapis.com/[redacted]

bundles:
  authz:
    service: gcs
    resource: [redacted]/bundle.tar.gz
    polling:
      min_delay_seconds: 5
      max_delay_seconds: 10
```

Arguments used to run this were 
```
opa run --server --config-file=config.yaml --watch -l debug /dir-with-bundle
```

You can see, that the first time, a bundle is downloaded without Etag and response 200. The second time, header `If-None-Match` is provided in the request and GCS returns 304 response. Third time, request is made without `If-None-Match`. The header is not present in the last request, because etag value is used from the previous response. However, the second response doesn't have etag header so it isn't provided in the next request.

**Comment by patrick-east** [comment] 2019-12-06 20:21
Can you check the bucket cache settings? Looking at your response headers the following things stand out:

```
        "Cache-Control": [
            "no-cache,max-age=0"
        ],
        "Date": [
            "Fri, 06 Dec 2019 09:48:44 GMT"
        ],
        "Expires": [
            "Fri, 06 Dec 2019 09:48:44 GMT"
        ],
```

You have more aggressive cache controls configured. Compare that to the defaults that were on my test bucket:
```
    "Cache-Control": [
      "public, max-age=3600"
    ],
    "Date": [
      "Mon, 02 Dec 2019 21:57:46 GMT"
    ],
    "Expires": [
      "Mon, 02 Dec 2019 22:57:46 GMT"
    ],
```

To repro I set my bucket to have the same metadata, and it starts to behave like yours (not returning an etag on subsequent requests):

![image](https://user-images.githubusercontent.com/3614287/70351121-12fe5f00-181d-11ea-9448-e4d80b38cd3d.png)

```
{11:52} ~ ❯ curl -sD - https://storage.googleapis.com/opa-bundles/b1.tar.gz -o /dev/null
HTTP/2 200
x-guploader-uploadid: AEnB2Uq1jfJYyNYU6jhnHWSGo3ASMQK6TK6HLhhNKRtJIzSee1zdNaUK_CY-qu67fk9qc-FsEJlX8kjuNriuJIOFE1l06W3tiIU9U0aI7pUk2JzbzUoqRm8
date: Fri, 06 Dec 2019 19:56:22 GMT
cache-control: no-cache, max-age=0
expires: Fri, 06 Dec 2019 19:56:22 GMT
last-modified: Mon, 02 Dec 2019 21:48:54 GMT
etag: "61f6cf0de9907870c7b1fbc97766a1d3"
x-goog-generation: 1575323334821453
x-goog-metageneration: 9
x-goog-stored-content-encoding: identity
x-goog-stored-content-length: 425
content-type: application/x-gzip
x-goog-hash: crc32c=w3PKFQ==
x-goog-hash: md5=YfbPDemQeHDHsfvJd2ah0w==
x-goog-storage-class: STANDARD
accept-ranges: bytes
content-length: 425
server: UploadServer
alt-svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000

{11:56} ~ ❯ curl -sD - -H 'If-None-Match: "61f6cf0de9907870c7b1fbc97766a1d3"'  https://storage.googleapis.com/opa-bundles/b1.tar.gz -o /dev/null
HTTP/2 304
x-guploader-uploadid: AEnB2Uqoqci4inWv_ILEEypJbA8UZV_HClCtYXql3bIdJJZgyayWMGfMZ7Fa5nYUZPcKU9Fl9JaofPNn49tEZgVKrMjUYC7xE2WNejvFQDLoqnxEiTvzLXI
date: Fri, 06 Dec 2019 19:56:29 GMT
cache-control: no-cache, max-age=0
expires: Fri, 06 Dec 2019 19:56:29 GMT
last-modified: Mon, 02 Dec 2019 21:48:54 GMT
content-length: 0
server: UploadServer
alt-svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000
```

Sooo. The API behavior is changing with the cache settings. If you set the `cache-control` back to `public` you'll get `ETag `'s in the response.

As-is I'm still of the opinion that OPA is behaving correctly WRT to the cache headers... I think it might be worth opening a support ticket with Google to see if they have any reason for why it wouldn't include the `ETag` on those 304's when set to `no-cache`. https://tools.ietf.org/html/rfc7232#section-4.1 is reasonable clear that the `ETag` should be present. Even something like https://redbot.org/?uri=https%3A%2F%2Fstorage.googleapis.com%2Fopa-bundles%2Fb1.tar.gz points out that required headers are missing.

As-is OPA is respecting the 304, and respecting that the next time it tries to make a request it doesn't have a token to validate with so it omits the header. While we can make this work by re-using old `ETag`s I'm concerned that we are changing OPA to behave in a way that might be unexpected for anyone implementing the bundle API's with custom services.

**Comment by patrick-east** [comment] 2019-12-06 20:44
Update: https://issuetracker.google.com/issues/145797604 is filed to track the issue over there.

**Comment by tsandall** [comment] 2020-01-09 16:40
Since OPA is doing the right thing (as far as we can tell) and someone from GCP engineering is going to look into this, I'm closing this issue for now.

**Closed by tsandall** 2020-01-09 16:40 UTC
