### ISSUE TITLE
In the rego playground, any() does not work as expected when used with functions

### ISSUE THREAD

**Issue by gregtczap** [open-policy-agent/opa#3239] opened 2021-03-09 05:27 UTC
## Expected Behavior

When using `any()` with a list of functions, `any()` should return true when any one of the functions returns true.

## Actual Behavior

Behaves like `all()` and only returns true when all of the functions return true.

## Steps to Reproduce the Problem

I have recreated this issue in the rego playground: https://play.openpolicyagent.org/p/50fMxIWvNV

```
package play

default allow = false

allow {
    any([
    	foo,
        bar
    ])
}

foo {
	false
}

bar {
	true
}
```

## Additional

I'm not actually sure whether this is a bug with `any()`, a bug with the rego playground, or intended behavior.

**Comment by anderseknert** [comment] 2021-03-09 05:54
What's happening here is that the `foo` rule does not evaluate to `false` but is rather undefined (as that is the default for non-truthy rules) and the presence of an undefined condition in the allow rule halts evaluation of the rule and the default value is used.

If you set `default foo = false` you'll see the allow rule evaluate to true as intended here.

**Comment by tsandall** [comment] 2021-03-09 14:51
I'm surprised to see that `any()` and `all()` are still in the built-in reference. I thought we hid them and deprecated them. Just write:

```
allow { foo }
allow { bar }
foo { false }
bar { true }
```.

**Comment by tsandall** [comment] 2021-03-09 16:02
I'm going to close this because there's nothing to do. @anderseknert would you want to put up a PR to hide the any() and all() functions from the built-in reference?

**Closed by tsandall** 2021-03-09 16:02 UTC
Labels: question

**Comment by anderseknert** [comment] 2021-03-09 16:04
Will do 👍

**Comment by gregtczap** [comment] 2021-03-09 18:23
@tsandall @anderseknert Thanks for the input... it makes sense why `any()` and `all()` are deprecated. If you're available for giving me a little direction, I'm still looking for a way to create a re-usable block of OR conditions that can nested inside of different allow blocks. While `any()` seemed preferable, I'm currently using a chain of evaluation blocks -- `{ }` -- to accomplish the same thing. Should I be using a different strategy to solve this problem?

https://play.openpolicyagent.org/p/7qvp0Hdnt1

```
package play

default allow = false

allow {
	
    path = "/dogs"
    verb = "GET"

    #any([foo, bar]) # more readable way to declare a list of OR conditions
    #[foo, bar][_] # still doesn't work due to a false condition halting the rest of the chain

    user_can_access
}

allow {
	
    path = "/cats"
    verb = "GET"

    #any([foo, bar]) # more readable way to declare a list of OR conditions
    #[foo, bar][_] # still doesn't work due to a false condition halting the rest of the chain

    user_can_access
}

# this method tests each block and returns true if any of them are true
# I need a way to repeat these tests across potentially hundreds of allow blocks
user_can_access {
	foo
} {
	bar
}

foo {
	false
}

bar {
	true
}

```

**Comment by gregtczap** [comment] 2021-03-09 19:19
For anyone else who may be referencing this issue looking for a way to evaluate a reusable list of OR blocks, I think in the end this method is the cleanest. As was pointed out above, the `any()` built-in could be considered syntactic sugar for this:

https://play.openpolicyagent.org/p/yf13X0po8L

```
package play

default allow = false

allow {
	
    path = "/dogs"
    verb = "GET"

    [foo, bar, baz][_] # returns true if any of the functions in the list return true
}

allow {
	
    path = "/cats"
    verb = "GET"

    [foo, bar, baz][_] # returns true if any of the functions in the list return true
}

default foo = false
foo {
	false
}

default bar = false
bar {
	true
}

default baz = false
baz {
	false
}
```

**Comment by anderseknert** [comment] 2021-03-09 19:22
I know it's just an example, but why add the extra indirection of the "foo" and "bar" rules rather than just having:

```rego
user_can_access {
	false
}
user_can_access {
	true
}
# Repeat as many times as necessary
```

An alternative if you need to track which rules exactly evaluated to true, you could use an incremental set rule, like:

```rego
user_can_access["foo"] {
	false
}
user_can_access["bar"] {
	true
}
```
Then simply check the contents of the set to see which rules have been true.

**Comment by gregtczap** [comment] 2021-03-09 20:04
@anderseknert In our real world implementation, those `foo` and `bar` blocks would encapsulate complicated sets of rules -- sometimes 5 or more lines -- I've just simplified them down to a single boolean to eliminate complexity for the examples so as not to confuse the point.

**Comment by anderseknert** [comment] 2021-03-09 20:08
OK @gregtczap .. yeah using default values is probably the way to go then. An alternative could be:
```rego
foo { true } else = false
bar { false } else = false
```
..but default rules feel like the better option here.

**Comment by gregtczap** [comment] 2021-03-09 20:22
@anderseknert Okay thanks for the confirmation. If I used that else syntax I would probably be explicit with the true clause so it reads better like so: `bar = true { true } else = false`. Also just to put it out there, this seems to be a good way to test a group of OR blocks as a named group:

https://play.openpolicyagent.org/p/o55u3B7jEC

```rego
package play

default allow = false

allow {
	
    path = "/dogs"
    verb = "GET"

    user_can_access[_] # returns true if any of the functions in the list return true
}

allow {
	
    path = "/cats"
    verb = "GET"

    user_can_access[_] # returns true if any of the functions in the list return true
}

user_can_access := [
    foo,
    bar,
    baz
]

default foo = false
foo {
	false
}

default bar = false
bar {
	true
}

default baz = false
baz {
	false
}
```

**Comment by anderseknert** [comment] 2021-03-09 20:36
Yep, alternatively you could use a set:

```rego
user_can_access := {
    foo,
    bar,
    baz,
    ...
}
```
And then check for `user_can_access[true]` .. which would require no iteration

**Comment by gregtczap** [comment] 2021-03-09 21:51
... and this has just circled back around to re-implementing something functionally similar to `any()` on the fly:

```rego
    any := {
    	foo,
        bar,
        baz
    }[true]
```

**Comment by anderseknert** [comment] 2021-03-09 21:58
Indeed 😄 And `all`:
```rego
all := {foo, bar, baz} == {true}
```

**Comment by anderseknert** [comment] 2023-08-23 05:06
You wouldn't be able to create a set of undefined values, if that's what you mean. Something like:

```rego
user_can_access := {
    "foo",
    input.bar,
}
```
Would have the whole set be undefined if `input.bar` was undefined.

Tangentially related, but these days it'd be considered better form to use `in` to check for membership:

```rego
# Prefer
true in my_set

# Over
my_set[true]
```

https://docs.styra.com/regal/rules/idiomatic/use-in-operator

**Comment by ckamzn** [comment] 2023-08-24 16:25
Thanks. Unfortunately, my organization is working with an incomplete and somewhat dated Rego parser implementation in Java, so `in` isn't an option for us. I really appreciate the clarification that a single undefined value will "undefine" the set.

**Comment by anderseknert** [comment] 2023-08-24 16:28
A Rego parser in Java? Intriguing! 😃
