### ISSUE TITLE
Website: Search Bar Missing in Reduced-Width Window

### ISSUE THREAD

**Issue by OBrienCommaJosh** [open-policy-agent/opa#3353] opened 2021-04-06 21:28 UTC
## Expected Behavior
As a user, I expect the search bar to persist when the browser window width is reduced.

## Actual Behavior
The search bar disappears when the window width is reduced and zoom is set above a certain threshold.

<img width="1440" alt="Full Screen (Search Bar Present)" src="https://user-images.githubusercontent.com/6808118/113780396-05dcd300-96e4-11eb-8db1-0aca93b3744b.png">

<img width="718" alt="Half Screen (Search Bar Missing)" src="https://user-images.githubusercontent.com/6808118/113780405-083f2d00-96e4-11eb-8828-f566eb1139f1.png">

## Steps to Reproduce the Problem
1. Navigate to https://www.openpolicyagent.org/docs/latest/
2. Reduce window width until search bar disappears.

## Additional Info
Browser: Firefox 87.0 (64-bit) & Chrome Version 89.0.4389.114 (Official Build) (x86_64)
OS: macOS 11.2.3

**Comment by saharme** [comment] 2021-05-05 11:02
Hi,
It is not a bug, it is a feature :)

This is because the media query should be lower than what is it now (set standard value). 
Now: 
(min-width: 1088px)

Should be ~:
(min-width: 600px)

**Comment by Parsifal-M** [comment] 2022-07-05 14:49
Hey Team,

Would it be okay if I pick this up? It will be my first contribution so if there is anything I should be aware of would be great! I am in the slack already :) 

Thanks!

**Comment by srenatus** [comment] 2022-07-05 15:00
Thank you - go for it! The situation around style sheets is quite opaque, I'm afraid, let us know if you get stuck.

**Comment by Parsifal-M** [comment] 2022-07-10 07:02
Hey @srenatus, I think I've found a good solution for this, I will make a PR later, are there any specific rules or best practices when making the PR? I may have missed them and this will be my first (and hopefully not last!)

Also, I forgot to ask, could you assign this to me?

Thanks!

**Comment by srenatus** [comment] 2022-07-10 07:56
Just open a PR. The checks, and the preview build on netlify, will give us a good indication of how it works. FWIW, our website stuff is a hodgepodge, so there aren't any guidelines or such a thing. Anything that works is OK 😅

**Closed** 2022-07-11 10:11 UTC
Labels: docs, good first issue
