### ISSUE TITLE
ability for `http.send` to halt policy evaluation on error even if `strict-builtin-errors` flag not set

### ISSUE THREAD

**Issue by jmoghisi** [open-policy-agent/opa#5805] opened 2023-03-31 13:45 UTC
## Underlying problem
The OPA documentation says that if `raise_error` is set, errors returned by `http.send` will halt policy evaluation, defaulting this to `true`. The documentation is a bit misleading as this only works when `--strict-builtin-errors` flag is set. 

We'd expect that an error returned by `http.send` should halt policy evaluation regardless of whether the strict builtin errors flag is set or not. 

If the server we are invoking is down we do not want to continue policy evaluation but we also do not want to enable errors for all other builtin functions.

## Proposed solution
The documentation for `raise_error` should be updated to reference `--strict-builtin-errors` flag.

We'd like the ability for `http.send` to halt policy evaluation on error **without** having other built-in functions halt policy evaluation on error as well. Changing the behaviour of `raise_error` flag would be a backwards incompatible break since it is defaulted to `true` but can a new `force_raise_error` flag be introduced to provide this behaviour?

**Comment by anderseknert** [comment] 2023-03-31 13:57
Hi @jmoghisi! I don't believe that is the intended behavior, so it's likely a bug if you're seeing that 🤔 

You're running `opa eval` and `raise_error` only works when `--strict-builtin-errors` is set, did I get that right?

**Comment by jmoghisi** [comment] 2023-03-31 16:29
Hi @anderseknert . Here's a simple example to reproduce:

```rego
package test

default allow = false

allow {
    response := http.send({
        "url": "http://localhost:8182",
        "method": "GET",
        "raise_error": true,
        "timeout": "1s"
    })
    response.status_code == 500
}
```

### Web server not running

Not halting policy evaluation without `--strict-builtin-errors`, despite `raise_error` being set:

```shell
$ opa.exe eval -b ./ "data.test" --format=pretty
{
  "allow": false
}
```

Halting policy evaluation with `--strict-builtin-errors`:
```shell
$ opa eval -b ./ "data.test" --strict-builtin-errors --format=pretty
1 error occurred: test\authz.rego:6: eval_builtin_error: http.send: Get http://localhost:8182: request timed out
```

### Web server returning 500
We see the following, regardless of whether we set  `--strict-builtin-errors` or not:

```shell
$ opa.exe eval -b ./ "data.test" --format=pretty
{
  "allow": true
}
```

Are 5xx errors not treated as errors...?

**Comment by anderseknert** [comment] 2023-04-03 06:53
That sounds like the intended behavior though, and I think the "halt policy evaluation" phrasing is what's possibly confusing here? It does not mean the entire evaluation will exit, but that the result of the `http.send` call will be undefined, meaning you don't get to handle it yourself unless the `raise_error` attribute is set to false.

If the remote server is not running, OPA the `http.send` call will fail, and allow rule will be assigned to its default value, which is `false`. If you set `raise_error` to false, you'll have a chance to capture the error in your policy and do something about it should you want that, but a timeout is not a 500 error. If you change that to `response.status_code == 0` it will "work".

**Comment by jmoghisi** [comment] 2023-04-04 10:17
## Documentation Issue

>  I think the "halt policy evaluation" phrasing is what's possibly confusing here?

Yes, this phrasing is causing confusion. The same wording is used to describe different behaviour in the [Policy Language](https://www.openpolicyagent.org/docs/latest/policy-language/#errors) document:

> By default, built-in function calls that encounter runtime errors evaluate to undefined (which can usually be treated as false) and do not halt policy evaluation. This ensures that built-in functions can be called with invalid inputs without causing the entire policy to stop evaluating.

Here, evaluating to `undefined` is considered as **not** halting policy evaluation, which contradicts your statement that halting policy evaluation means resulting in `undefined`, no?

The http.send documentation should also be updated to reference that `raise_error` only raises an error if `strict-builtin-errors` flag is set :)

## Underlying Problem

We are trying to handle a case where our downstream service called by OPA is unhealthly (either down or returning 500s) and our Policy cannot be used to make a decision. Ideally we want to bubble this error up to the client so that it could decide what to do e.g. retry with a backoff, trigger circuit breaker, fail, etc. 

The current behaviour means that the client cannot tell the difference between OPA returning a deny decision and being unable to make a decision - HTTP status codes seemed like the most appropriate way to communicate this.

**Comment by anderseknert** [comment] 2023-04-04 11:59
> Yes, this phrasing is causing confusion. 

An update to the docs would be welcome :)

> The http.send documentation should also be updated to reference that raise_error only raises an error if strict-builtin-errors flag is set :)

No, it'll work as intended without `strict-builtin-errors`, which is to return a "response" with error details — either from the server, or "generated" ones in case of e.g. a timeout. This is to allow you to handle this scenario from inside of your policy, which seems to be what you want. Note that `strict-builtin-errors` isn't even an option when running OPA as a server, which is the more common mode of operation.

**Comment by anderseknert** [comment] 2023-04-04 12:21
Here's an example you can try:

```rego
package p

response := http.send({
    "url": "https://httpbin.org/delay/1",
    "method": "GET",
    "timeout": "5ms",
})
```
This obviously will time out, so let's see what happens with and without `raise_error`. As the value is `true` by default, evaluating the response gives us:

```
opa eval -f pretty -d http.rego data.p.response
undefined
```
Setting the flag to `false`:

```rego
package p

response := http.send({
    "url": "https://httpbin.org/delay/1",
    "method": "GET",
    "timeout": "5ms",
    "raise_error": false,
})
```
```
opa eval -f pretty -d http.rego data.p.response
{
  "error": {
    "code": "eval_http_send_network_error",
    "message": "Get \"https://httpbin.org/delay/1\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
  },
  "status_code": 0
}
```

**Comment by jmoghisi** [comment] 2023-04-05 12:49
thanks for explaining. what do you recommend we do in our scenario? 

it would have been much more convenient to retry / trigger circuit breaker based on HTTP status codes... could a feature be added to always raise an error (and not just halt policy evaluation with `undefined`), even if `--strict-builtin-errors` is not set? and could this be done for 5xx errors too?

**Comment by anderseknert** [comment] 2023-04-05 13:14
Just set the `raise_error` flag to `false` and check for `status_code == 0` for errors in the request/response, and `status_code == 500` for errors from the server. Extremely simplified, but something like:

```rego
package p

response := http.send({
    "url": "https://httpbin.org/delay/1",
    "method": "GET",
    "timeout": "1s",
    "raise_error": false,
})

handle_response(response) := msg {
    response.status_code == 0

    msg := sprintf("error connecting to server: %v", [response])
}

handle_response(response) := msg {
    response.status_code > 499

    msg := sprintf("error from server: %v", [response])
}

handle_response(response) := msg {
    response.status_code > 199
    response.status_code < 300

    msg := sprintf("yay! %v", [response])
}


decision := handle_response(response)
```

**Comment by jmoghisi** [comment] 2023-04-05 15:06
no worries, we were hoping there was a way to rely on HTTP status codes to bubble up and communicate errors rather than have to update all of our clients to parse the response body.

**Comment by anderseknert** [comment] 2023-04-05 18:02
> helper functions need to return an Either-like return value containing either the result or an error

That's already done by the `handle_response` function in my example, as their condtionas are mutually exclusive. 

But I hear what you're saying now — had not understood about your request to have the OPA server return different status codes. You're right — the client needs to parse the response.

**Comment by jmoghisi** [comment] 2023-04-06 08:16
in our policies, the same `http.send` is reused in a function that takes as argument input from other policies. it will need a bit of refactoring but we can make the above work...

having said that, we also use `http.send` in the `system.authz` policy. we can use the `reason` field in the response to communicate back the error the response format is inconsistent with our own policies, further complicating the client error handling. we have multiple, polygot clients so this is not simple for us to maintain, some owned by other teams/developers.

should `http.send` provide the ability to  _fully_ halt policy evaluation and bubble up the error by returning 500 status code? it will simplify our client error handling (by not requiring any changes) and avoid the need to refactor our policies.

**Comment by anderseknert** [comment] 2023-04-06 09:31
Rules or functions that return errors/undefined aren't treated as special in OPA. For a whole bunch of policies, an undefined or empty result is what you _want_ OPA to return, i.e:

```rego
deny if {
    # some conditions here which hopefully are undefined
}
```

Having a policy decide the status code (or as sometimes requested, response headers) to return would create a hard coupling between the policy and the OPA _server_, which would be undesirable. As you're own experiments using `opa eval` have shown, running OPA as a server is only one of many options to evaluate a policy (`opa eval`, `opa test`, `opa exec`, etc) and having to make them aware of what a "status code" or response headers are, would be contrived at best.

**Comment by anderseknert** [comment] 2023-04-06 09:33
I'll close the issue, but I'm happy to keep the discussion open :)

**Closed by anderseknert** 2023-04-06 09:33 UTC
Labels: waiting-for-response

**Comment by jmoghisi** [comment] 2023-04-06 13:40
agree that it's not desirable to create a hard coupling with the OPA server and ignore `opa eval`, `opa test`, etc but that is not my suggestion. `strict-builtin-errors` returns a 500 error code when running as a server but throws an error with `opa eval` and terminates execution, for example.

could `http.send` not do something similar here by providing an option to always throw an error on IO errors or 5xx responses?

**Comment by anderseknert** [comment] 2023-04-06 14:06
I'm not sure what you mean. There's no `strict-builtin-errors` flag for the `run` command that I'm aware of?

**Comment by jmoghisi** [comment] 2023-04-06 14:40
The OPA documentation mentions it's available for `opa run` too, see [Policy Language](https://www.openpolicyagent.org/docs/latest/policy-language/#errors) . Though I just tried it and it didn't work... so it seems like another documentation issue. Fair enough, will close the discussion.

**Comment by anderseknert** [comment] 2023-04-06 20:53
No, you're right — there is no such flag for `opa run`, **but** I wasn't aware you could pass it as a query parameter in the request. Will have to try that.
