### ISSUE TITLE
Incremental rules combining wasm & "entrypoint: true" annotations leads to unexpected results

### ISSUE THREAD

**Issue by robertgartman** [open-policy-agent/opa#5565] opened 2023-01-16 12:22 UTC
## Short description 
Use of `entrypoint: true` annotation generates unexpected results when building wasm and based on [incremental rules](https://www.openpolicyagent.org/docs/latest/policy-reference/#incremental). Current (v0.48) [documentation](https://www.openpolicyagent.org/docs/latest/annotations/) states that  `entrypoint: true` can be applied on either package or rule level. Nothing is mentioned whether incremental rules should be treated in a special way. So... wrong usage, undocumented features ... or code bugs(s)? Not sure.

Output from `opa version`:
```
Version: 0.48.0
Build Commit:
Build Timestamp:
Build Hostname:
Go Version: go1.19.4
Platform: darwin/arm64
WebAssembly: unavailable
```

### Test 1
```
# METADATA
# entrypoint: true
package testing

import future.keywords

constant_without_annotation := {"a", "b"}

without_annotation if {
	input == "whatever"
}

incremental_without_annotation[x] if {
	constant_without_annotation[x]
	without_annotation
}

# METADATA
# entrypoint: true
with_annotation := true
```

Save the file in a folder, and within that folder run:
```
opa check --strict *.rego && \
opa build -t wasm *.rego -o /tmp/bundle.tar.gz && \
tar xzf /tmp/bundle.tar.gz --directory . /.manifest
```

The extracted `.manifest` contains these entrypoints:
"testing", "testing/with_annotation", "testing/incremental_without_annotation"

### Test 1 expected behavior
According to the docs, "testing/incremental_without_annotation" shouldn't be included. But it is, thanks to the package level annotation, which is not intuitive.

### Test 2
```
package testing

import future.keywords

constant_without_annotation := {"a", "b"}

# METADATA
# entrypoint: true
incremental_without_annotation[x] if {
	constant_without_annotation[x]
	without_annotation
}
```
Run:
```
opa check --strict *.rego && \
opa build -t wasm *.rego -o /tmp/bundle.tar.gz
```
Result: code passing `check` but failing on `build`with
> error: unresolved reference (indicates error in caller): data.testing.incremental_without_annotation[x]

### Test 2 expected behavior
Passing and be part of the resulting entrypoints

### Test 3 bonus
Revisiting the policy file of test 1, run:
```
opa build -t wasm *.rego -o /tmp/bundle.tar.gz && \
opa inspect /tmp/bundle.tar.gz 
```
`inspect` complains about the rule level annotation:
> /testing.rego:16: rego_parse_error: invalid annotation scope ''
> /testing.rego:16: rego_parse_error: annotation entrypoint applied to non-rule or package scope ''
### Test 3 expected behavior
No complains

**Comment by anderseknert** [comment] 2023-01-16 14:18
Thanks Robert! That does indeed look like some real issues. Just out of curiousity — and potentially as a workaround until this has been addressed — have you tried doing this without annotations? You could instead use the `--entrypoint` flag with `opa build` and have it point to the same rules/packages as you would using annotations. It'd be good to know if the problem comes from the annotations (which I think is likely) or the entrypoint logic itself.

**Comment by robertgartman** [comment] 2023-01-16 15:53
Checking **without** annotations. Source:
```
package testing

import future.keywords

constant_without_annotation := {"a", "b"}

without_annotation if {
	input == "whatever"
}

incremental_without_annotation[x] if {
	constant_without_annotation[x]
	without_annotation
}

with_annotation := true
```

Command:
```
opa check --strict *.rego && \
opa build -t wasm *.rego -o /tmp/bundle.tar.gz \
-e testing/constant_without_annotation \
-e testing/without_annotation \
-e testing/incremental_without_annotation && \
tar xzf /tmp/bundle.tar.gz --directory . /.manifest
```

Note that `with_annotation` is not part of the included entrypoints.

Resulting `.manifest` (formatted):
```
{
    "revision": "",
    "roots": [
        ""
    ],
    "wasm": [
        {
            "entrypoint": "testing/constant_without_annotation",
            "module": "/policy.wasm"
        },
        {
            "entrypoint": "testing/without_annotation",
            "module": "/policy.wasm"
        },
        {
            "entrypoint": "testing/incremental_without_annotation",
            "module": "/policy.wasm"
        },
        {
            "entrypoint": "testing/with_annotation",
            "module": "/policy.wasm"
        }
    ]
}
```

Conclusion: Incremental rules can be included. But... **testing/with_annotation** is joining the party without invitation.

**Comment by anderseknert** [comment] 2023-01-16 17:09
That's useful, thanks Robert. Sounds like your temporary workaround is to provide entrypoints as arguments over annotations then. While the extra entrypoint is annoying, at least it "works" until we've had a chance to look into this. Thanks for all the detailed examples!

**Comment by johanfylling** [comment] 2023-01-20 13:25
For easier tracking, I have created a separate bug report (#5577) for `Test 2`, as it's origins can be isolated from the other behavior described in this ticket.

**Comment by johanfylling** [comment] 2023-01-23 17:54
@robertgartman, the extra entrypoints you're seeing aren't added due to being "incremental". `incremental_without_annotation` is enumerated as an entrypoint because it's referencing declared entrypoints: `testing.with_annotation` and `testing.constant_without_annotation` (the latter is a transitive reference via the `testing` package). You can side-step this behavior by also submitting the `--prune-unused` flag to the `build` command.
I will update the docs to highlight this behavior in the next release.

Scenario `Test 2` is a confirmed bug (#5577), that will get fixed in the next release.
Scenario `Test 3` is a possible bug, that'll get investigated further.

**Closed** 2023-01-23 19:31 UTC
Labels: bug

**Comment by johanfylling** [comment] 2023-01-24 13:22
Scenario `Test 3` has been confirmed as a bug: #5588
