### ISSUE TITLE
Incorrect AWS Sigv4 signature when specifying version of S3 object as URL Parameter

### ISSUE THREAD

**Issue by senaas1995** [open-policy-agent/opa#4954] opened 2022-08-01 16:32 UTC
## Short description 

We are using opa's discovery feature to dynamically download s3 bundles. Our policy file looks as shown below. This policy successfully downloads and activates "/main_bundle/authz.tar.gz".

```
package discovery

bundle_config := {
  "bundles": {
    "main": {
      "service": "s3_service",
      "resource": bundle_name
    },
  },
  "default_decision": "/authz/allow",
  "default_authorization_decision": "/authz/allow"
}

bundle_name := "/main_bundle/authz.tar.gz"
```

The issue happens when we try to download a certain version of this main_bundle. i.e the below policy gives us 403 error on S3.
```
package discovery

bundle_config := {
  "bundles": {
    "main": {
      "service": "s3_service",
      "resource": bundle_name
    },
  },
  "default_decision": "/authz/allow",
  "default_authorization_decision": "/authz/allow"
}

bundle_name := "/main_bundle/authz.tar.gz?versionId=XYZ" //where XYZ is the versionId
```

From the S3 perspective, the error is being thrown specifically from a 'SignatureDoesNotMatch' error due to the requester information. Instead of the IAM ID and session being passed, S3 is not receiving either of these values resulting in the signature mismatch when S3 tries to verify the signature.

I can see the correct url being created and sent to S3. We suspect the issue is happening because of the url parameters given after the "?",  in this case versionId which is resulting in sigv4 mismatch. 

One possible solution could be to add some extra parameters for bundle configuration or update OPA's aws authentication plugin to exclude anything after "?" in URL.

## Expected behavior

OPA Should be able to download S3 versioned objects from the past by specifying version Id in the bundle_name as shown in above example.

## Additional context

Boot Config is shown below (actual 

services:
  s3_service:
    url: ${S3_BASE_PATH} //hard data hidden for obvious reasons
    response_header_timeout_seconds: 5
    credentials:
      s3_signing:
        metadata_credentials:
          aws_region: ${AWS_DEFAULT_REGION}

discovery:
  resource: /discovery/discovery.tar.gz
  decision: discovery/bundle_config
  polling:
    min_delay_seconds: 10
    max_delay_seconds: 20

**Comment by LuckySpb** [comment] 2022-08-01 17:34
This issue is not related to discovery bundle configuration, it can be easily reproduced with simple bundle configuration with s3_sigining and specifying explicit version.

The issue is that sigv4 validations expects only resource path to be used in signature creation excluding query parameters

So for full url like 
`https://my-opa-bundle.s3.amazonaws.com/bundles/authz.tar.gz?versionId=XYZ` 
only 
`https://my-opa-bundle.s3.amazonaws.com/bundles/authz.tar.gz` 
should be used for sigv4 signature creation


Alternative fix to the proposed in the original post is to just exclude query parameters in s3_signing plugin.

**Comment by anderseknert** [comment] 2022-08-01 19:18
The query string can't be dropped from the signing process if present in the request — in fact, that [we do so today](https://github.com/open-policy-agent/opa/blob/main/plugins/rest/aws.go#L588) is the cause of the issue you are reporting 🙂 See the [canonical request](https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html) section of the AWS docs for what we should do here. 

Should be fairly easy to fix 🤞😅 If you'd want to give it a shot, that'd be great! If not we can mark it as a good first issue to see if someone else wants to pick it up.

**Comment by anderseknert** [comment] 2022-08-01 19:37
Done 👍 Only caveat is that one will need an actual AWS account and a bucket set up in order to properly test this, but not a huge hurdle.

**Comment by LuckySpb** [comment] 2022-08-01 22:59
I had setup S3 buckets to fully reproduce the issue
https://github.com/LuckySpb/opa-s3-sigv4

One bucket is fully public, so config with version id works fine.
Another bucket requires authentication (available for any authenticated user), so config without version works fine, config with version fails

```
# good - need auth
opa run --server --config-file opa-config-auth-no-version.yaml --log-level debug

# bad - need auth - version specified
opa run --server --config-file opa-config-auth-with-version.yaml --log-level debug
```

**Comment by sinhaaks** [comment] 2022-08-04 09:29
Can I work on this issue?

**Comment by anderseknert** [comment] 2022-08-04 09:44
@sinhaaks of course 👍 assigning to you

**Comment by sinhaaks** [comment] 2022-08-06 07:47
> @sinhaaks of course 👍 assigning to you

Thank yu

**Comment by sinhaaks** [comment] 2022-08-06 07:57
> @sinhaaks of course 👍 assigning to you

Thank you

**Comment by sinhaaks** [comment] 2022-08-06 21:41
I have created a PR, can you please review, I'm not able to add reviewers - https://github.com/open-policy-agent/opa/pull/4977

**Closed** 2022-08-09 11:45 UTC
Labels: bug, good first issue
