### ISSUE TITLE
CLI: "too many open files" when using --bundle flag

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#3777] opened 2021-09-06 14:33 UTC
##  Actual Behavior vs. Expected Behavior

When using large bundles, or directories "as" bundles using the `--bundle`/`-b` flag, OPA seems to claim an open file handle for each file in the bundle. On Mac this limit is by default rather conservative at 256 (as seen from `ulimit -n`), leading to errors such as:

```shell
$ opa run -b .
error: load error: bundle .: bundle read failed: failed to open file p92.rego: open p92.rego: too many open files
```

Note that this does not happen without the `--bundle` flag (i.e. `opa run .`) leading me to believe we could handle this better in OPA.

## Steps to Reproduce the Problem

```shell
$ ulimit -a
...
open files                          (-n) 256
```

In a temporary directory, create more policy files than the allowed number of open files:

```shell
#!/usr/bin/env bash

for i in {0..256}; do
	cat <<- EOF > "p$i.rego"
	package p$i

	allow := true
	EOF
done
```

You should now be able to see that `opa run .` successfully starts the OPA REPL, while `opa run -b .` results in:

```shell
error: load error: bundle .: bundle read failed: failed to open file p92.rego: open p92.rego: too many open files
```

**Comment by bhoriuchi** [comment] 2021-09-09 19:37
How many files are in the bundle causing the issue? I attempted to reproduce with a data bundle containing ~1000 directories and 528 data.json files and was not able to. I am on a macbook and my file descriptor limit is also the default 256. I am looking to add quite a few more files/directories and would like to understand any considerations i need to make to accomplish that.

**Comment by anderseknert** [comment] 2021-09-09 20:56
That’s definitely useful. Thanks for the additional details @bhoriuchi! 👍

**Comment by bhoriuchi** [comment] 2021-09-11 01:28
well, i suppose i spoke too soon. it seems the issue is with json files as well, i just happened to run the test with json files in a terminal that had a higher limit. I have however traced the issue down to this line of code https://github.com/open-policy-agent/opa/blob/main/bundle/file.go#L133 which opens all of the file before it processes them. i think the only way around this is to open the files later in the process (like here https://github.com/open-policy-agent/opa/blob/main/bundle/bundle.go#L402) and close them immediately.

**Comment by anderseknert** [comment] 2021-09-11 01:39
Yeah, that or open them in batches of something like 16. If you’d like to take a shot at a PR, that’d be very welcome 😊

**Comment by bhoriuchi** [comment] 2021-09-11 03:14
Sure, after looking at it again I think we can just read the file in the walk then close it and use bytes.NewReader to pass a reader instead of the file handle for the descriptor

**Comment by bhoriuchi** [comment] 2021-09-11 13:11
after some git hijinks with my first PR, i have submitted a second with the LazyFile implemented. 

```
➜  opa git:(main) ulimit -n
256
```

0.32
```
➜  opa git:(main) ✗ opa run -b ~/bundletest
error: load error: bundle /***/bundletest: bundle read failed: failed to open file /***/bundletest/p90.rego: open /***/bundletest/p90.rego: too many open files
```

Dev build
```
➜  opa git:(main) ✗ ./opa run -b ~/bundletest
OPA 0.33.0-dev (commit , built at )

Run 'help' to see a list of commands and check for updates.

> data.p256
{
  "allow": true
}
> exit
```

**Closed** 2021-09-13 07:38 UTC
