### ISSUE TITLE
repl: nested expressions not assigned with =

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#1104] opened 2018-12-08 17:08 UTC
# Expected Behavior

Nested expressions that look like assignment should be treated as such in the REPL.

# Actual Behavior

Nested expressions are evaluated as queries. For example, the following expression does not define a new rule 'x'.

```
x = 1+1
```

As a top-level statement in a Rego file, 'x' would be defined as a rule.

# Additional Info

This is likely an issue to do with the evalStatement function in the REPL where we try to convert AST statements into rules. If the statement is rewritten as `x := 1+1` then a rule is defined as expected.

Note, in `x = 1+1` 'x' could refer to another rule in which case the statement should just be evaluated. The REPL should compile/resolve references in the statement and then rely on the parsed AST to decide whether a rule should be defined.

**Comment by srenatus** [comment] 2019-01-08 14:12
Isn't this a duplicate of #726? It does have more information, though; we could consider merging them. 🤔

**Comment by tsandall** [comment] 2019-01-08 17:53
@srenatus indeed. I'm going to close the other one in favour of this one.

**Closed** 2019-05-19 04:27 UTC
Labels: bug
