### ISSUE TITLE
Queued decision logs lost on opa server shutdown

### ISSUE THREAD

**Issue by gshively11** [open-policy-agent/opa#2754] opened 2020-10-06 16:26 UTC
## Expected Behavior

When there are decision logs queued but not yet sent to the target service, shutting down the OPA server gracefully should flush the remaining decision logs to the target service before terminating the process.

## Actual Behavior

The server shuts down without flushing queued decision logs and the logs are lost.

## Steps to Reproduce the Problem

OPA version: 0.24.0-dev

**Comment by tsandall** [comment] 2020-10-06 16:55
This is a dupe of #780 and there's actually an open PR for it right now: https://github.com/open-policy-agent/opa/pull/2746. Closing.

**Closed by tsandall** 2020-10-06 16:55 UTC

**Comment by gshively11** [comment] 2020-10-06 17:03
My bad, thanks!
