### ISSUE TITLE
Opa PUT data requests taking 3-4 seconds

### ISSUE THREAD

**Issue by mcieplak** [open-policy-agent/opa#1786] opened 2019-09-23 06:12 UTC
We are replicating a variety of Kubernetes resources through the use of kube-mgmt within our clusters, this includes deployments, ingress, and a couple of istio custom resources. The issue we’re facing is the PUT requests are taking a significant amount of time, up to 3-4 seconds per call. The larger the amount of resources, the more time it takes for the request to finish. In the case of deployments, we have roughly 1400 resources within the cluster. Just one PUT request to update one deployment resource will take the 3-4s mentioned previously. I believe this may be due to the fact that the in memory database has a write lock around it where we are spending a significant amount of time waiting  here since we receive so many updates from the Kubernetes api server.

Here is the average response duration we are seeing for PUT requests to the opa container.
<img width="1668" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/10733268/65404643-40934a80-dd8e-11e9-9e74-6b56c367de5b.png">

This is the synchronization blocking profile from go trace showing the Lock is taking up a substantial amount of time.
<img width="642" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/10733268/65404653-4a1cb280-dd8e-11e9-9b08-f5ef8152640c.png">

Are there any optimization / configuration changes we can make to improve this time?

**Comment by tsandall** [comment] 2019-09-23 13:32
@mcieplak what version of OPA are you running?

**Comment by tsandall** [comment] 2019-09-23 13:38
This looks like it's related to the high latency in https://github.com/open-policy-agent/opa/issues/1786

**Comment by mcieplak** [comment] 2019-09-23 18:58
@tsandall We have been running with version `0.10.5` for quite some time where we've been seeing this issue. We have also tried running `0.14.0` and saw the same behavior.

Can you share which issue the high latency is related to? That link points to this issue. Thanks!

**Comment by patrick-east** [comment] 2019-09-23 21:42
@mcieplak Couple of questions to help us troubleshoot a little bit more and repro the issue:

Do you have an estimate of the request frequency you're seeing? The issue mentions:

> we receive so many updates from the Kubernetes api server.

And maybe I'm missing it, but I don't see in the diagrams/charts anywhere that mentions how many requests were being processed. I'm guessing it is a lot.. otherwise threads wouldn't be waiting on the storage transaction so much, but I'd like to get a better sense of how many.

I'm not super familiar with the kube-mgmt code, but if I'm reading this part correctly we PUT individual objects https://github.com/open-policy-agent/kube-mgmt/blob/master/pkg/data/generic.go#L205 If the issue is that we're hammering OPA with too many PUT's maybe we can do some better batching or something in kube-mgmt.

Will also look to see if we can do anything to help with the locking in OPA. Once we can get a repro of the poor performance it will be easier to determine how much room we have to work with there.

**Comment by mcieplak** [comment] 2019-09-24 01:25
@patrick-east We are running kube-mgmt version 0.9 with kubernetes 1.13.7.

Currently we are getting roughly 4-5 RPS for each OPA pod (2 replicas).

Here is some more information from the go routine trace which shows an idea of how many requests were occurring at once in the server.
![Screen Shot 2019-09-23 at 6 11 30 PM](https://user-images.githubusercontent.com/10733268/65473678-9c60e080-de2d-11e9-9983-dbafa3d814f3.png)

Yes, I believe each individual kubernetes resource will be their own PUT request which means the main database in OPA will be constantly locked / unlocked. I agree, maybe some sort of batching here would improve the performance.

The best way to reproduce would be to create a large amount of kubernetes resources which are constantly being updated so they trigger the watch notifications to the kube-mgmt container which will translate into a large amount of PUT requests to OPA.

**Comment by patrick-east** [comment] 2019-09-25 16:54
Thanks for the info @mcieplak !

Two more questions 😄 

Do you have any resource constraints configured for OPA?
Do you have any details about resource usage for the host and what the OPA container was using?

**Comment by patrick-east** [comment] 2019-10-01 18:15
@mcieplak We've updated kube-mgmt with https://github.com/open-policy-agent/kube-mgmt/pull/50 (related to another reported issue) that might help somewhat with too many PUT requests when a full resync happens.

For the case of the updates being slow the only way I was able to reproduce that was by limiting OPA's CPU and memory resources and essentially overloading the API handlers. If you have an details about resource usage of your OPA containers and the nodes that they are running on it would be helpful for us as right now the current theory is that OPA just doesn't have enough resources to process them fast enough. In that situation the case of seeing threads waiting on the storage transaction lock is expected. The 3-4 seconds however is very slow, so if it _isn't_ starved on CPU or memory we would like to continue investigating what might be different in you're environment from ours (we can't reproduce the same latency in normal conditions on our test clusters).

**Comment by mcieplak** [comment] 2019-10-09 03:08
@patrick-east 

The resource limits which we're running are the following:
Opa: 10 cpu and 4 Gi memory
Kube-mgmt: 1 cpu and 2 Gi memory

The deployment itself is running around ~30% cpu utilization and ~12% memory so we are not actually seeing any resource constraints. The resource utilization on the node is also extremely low as they are pretty large in terms of cpu / memory.

I will run the newest kube-mgmt with the linked PR change above and also report on what type of differences we are seeing in performance.

**Comment by patrick-east** [comment] 2019-12-17 01:40
@mcieplak re:

> I will run the newest kube-mgmt with the linked PR change above and also report on what type of differences we are seeing in performance.

Any update?

**Comment by tsandall** [comment] 2020-04-15 19:21
Closing this issue for now. We can re-open if needed or if there are updates that indicates it's still a problem.

**Closed by tsandall** 2020-04-15 19:21 UTC
Labels: investigating
