### ISSUE TITLE
Local Build Failure

### ISSUE THREAD

**Issue by ajanthan** [open-policy-agent/opa#3072] opened 2021-01-18 18:37 UTC
Unable to build the master branch.

## Expected Behavior
Successful build

## Actual Behavior
Build fails with the following error.
`
clang-11  -std=c++17 -MD -MP -nodefaultlibs --target=wasm32-unknown-unknown-wasm -fno-exceptions -fno-rtti -I src/lib -I src/libc++ -I /usr/lib/llvm-11/include/c++/v1 -I /usr/lib/llvm-11/lib/clang/11.0.0/include -I src/re2 -D_LIBCPP_HAS_NO_THREADS -O3   src/libc++/mutex.cc   -o src/libc++/mutex

clang: error: unable to execute command: Executable "wasm-ld" doesn't exist!
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [<builtin>: src/libc++/mutex] Error 1
make[1]: *** [build] Error 2
make: *** [wasm-lib-build] Error 2
`

## Steps to Reproduce the Problem
Issue make command on the freshly cloned master branch

**Comment by ashutosh-narkar** [comment] 2021-01-18 18:45
Try doing a `make clean` and then make sure you have the latest `openpolicyagent/opa-wasm-builder` image. Finally check if the if wasm/src/libc++/mutex.d  is present. A  `git status` will do.

**Comment by ajanthan** [comment] 2021-01-19 07:55
@ashutosh-narkar 

1.  Issued `make clean`
2.  `docker pull openpolicyagent/opa-wasm-builder:1.2` ->
> Pulling from openpolicyagent/opa-wasm-builder
> Digest: sha256:fbba81d016bb95b88773947d107e4e1abef8b0adcd9fc81687887aca9e980ff0
> Status: Image is up to date for openpolicyagent/opa-wasm-builder:1.2
> docker.io/openpolicyagent/opa-wasm-builder:1.2

3. `ls wasm/src/libc++/mutex.d` ->

> wasm/src/libc++/mutex.d

 it solves the previous error but now,  there is a new error.

> clang-11 -std=c++17 -MD -MP -nodefaultlibs --target=wasm32-unknown-unknown-wasm -fno-exceptions -fno-rtti -I src/lib -I src/libc++ -I /usr/lib/llvm-11/include/c++/v1 -I /usr/lib/llvm-11/lib/clang/11.0.0/include -I src/re2 -D_LIBCPP_HAS_NO_THREADS -O3 -c -o _obj/src/re2/re2/dfa.wasm src/re2/re2/dfa.cc
In file included from src/re2/re2/dfa.cc:41:
src/re2/util/mutex.h:37:14: error: no type named 'mutex' in namespace 'std'
typedef std::mutex MutexType;
        ~~~~~^
src/re2/util/mutex.h:96:36: error: member reference base type 'MutexType' (aka 'int') is not a structure or union
void Mutex::Lock()         { mutex_.lock(); }
                             ~~~~~~^~~~~
src/re2/util/mutex.h:97:36: error: member reference base type 'MutexType' (aka 'int') is not a structure or union
void Mutex::Unlock()       { mutex_.unlock(); }
                             ~~~~~~^~~~~~~
3 errors generated.
make: *** [Makefile:135: _obj/src/re2/re2/dfa.wasm] Error 1
make[1]: *** [build] Error 2
make: *** [wasm-lib-build] Error 2

**Comment by ashutosh-narkar** [comment] 2021-01-19 17:54
Do a `git status` to check if `wasm/src/libc++/mutex` is deleted. If yes, do a `git checkout` on it.

**Comment by tsandall** [comment] 2021-01-20 16:40
This is likely caused by an out-of-date working copy. Closing the issue.

**Closed by tsandall** 2021-01-20 16:40 UTC
