### ISSUE TITLE
concurrency issues in types.Compare()

### ISSUE THREAD

**Issue by markushinz** [open-policy-agent/opa#3793] opened 2021-09-15 09:25 UTC
## Expected Behavior

I can concurrently create multiple compilers and compile modules. More concrete, I can run a function as the following at the same time in multiple go routines.

```go
func getCompiler(modules map[string]*ast.Module) (*ast.Compiler, error) {
	compiler := ast.NewCompiler()
	compiler.Compile(modules)
	if compiler.Failed() {
		return nil, compiler.Errors
	}
	return compiler, nil
}
```

## Actual Behavior

The above code shows a race condition:

```log
WARNING: DATA RACE
Read at 0x00c0001d8930 by goroutine 118:
  github.com/open-policy-agent/opa/types.typeSlice.Less()
      /Users/markushinz/go/pkg/mod/github.com/open-policy-agent/opa@v0.32.0/types/types.go:867 +0x70
  github.com/open-policy-agent/opa/types.(*typeSlice).Less()
      <autogenerated>:1 +0x24
  sort.insertionSort()
      /opt/homebrew/Cellar/go/1.17/libexec/src/sort/sort.go:40 +0xd4
  sort.quickSort()
      /opt/homebrew/Cellar/go/1.17/libexec/src/sort/sort.go:222 +0x1dc
  sort.Sort()
      /opt/homebrew/Cellar/go/1.17/libexec/src/sort/sort.go:231 +0x7c
  github.com/open-policy-agent/opa/types.Compare()
      /Users/markushinz/go/pkg/mod/github.com/open-policy-agent/opa@v0.32.0/types/types.go:628 +0xd44
  github.com/open-policy-agent/opa/ast.unify1()
      /Users/markushinz/go/pkg/mod/github.com/open-policy-agent/opa@v0.32.0/ast/check.go:450 +0x17c
  github.com/open-policy-agent/opa/ast.(*typeChecker).checkExprBuiltin()
      /Users/markushinz/go/pkg/mod/github.com/open-policy-agent/opa@v0.32.0/ast/check.go:336 +0x9cc
  github.com/open-policy-agent/opa/ast.(*typeChecker).checkExpr()
      /Users/markushinz/go/pkg/mod/github.com/open-policy-agent/opa@v0.32.0/ast/check.go:287 +0x218
  github.com/open-policy-agent/opa/ast.(*typeChecker).CheckBody.func1()
      /Users/markushinz/go/pkg/mod/github.com/open-policy-agent/opa@v0.32.0/ast/check.go:119 +0x3ac
  github.com/open-policy-agent/opa/ast.WalkExprs.func1()
      /Users/markushinz/go/pkg/mod/github.com/open-policy-agent/opa@v0.32.0/ast/visit.go:208 +0x54
  github.com/open-policy-agent/opa/ast.(*GenericVisitor).Walk()
      /Users/markushinz/go/pkg/mod/github.com/open-policy-agent/opa@v0.32.0/ast/visit.go:273 +0x5c
  github.com/open-policy-agent/opa/ast.(*GenericVisitor).Walk()
      /Users/markushinz/go/pkg/mod/github.com/open-policy-agent/opa@v0.32.0/ast/visit.go:314 +0xe08
  github.com/open-policy-agent/opa/ast.WalkExprs()
      /Users/markushinz/go/pkg/mod/github.com/open-policy-agent/opa@v0.32.0/ast/visit.go:212 +0x64
  github.com/open-policy-agent/opa/ast.(*typeChecker).CheckBody()
      /Users/markushinz/go/pkg/mod/github.com/open-policy-agent/opa@v0.32.0/ast/check.go:102 +0xb8
  github.com/open-policy-agent/opa/ast.(*typeChecker).checkClosures.func1()
      /Users/markushinz/go/pkg/mod/github.com/open-policy-agent/opa@v0.32.0/ast/check.go:161 +0x810
  github.com/open-policy-agent/opa/ast.WalkClosures.func1()
      /Users/markushinz/go/pkg/mod/github.com/open-policy-agent/opa@v0.32.0/ast/visit.go:160 +0xc8
  github.com/open-policy-agent/opa/ast.(*GenericVisitor).Walk()
      /Users/markushinz/go/pkg/mod/github.com/open-policy-agent/opa@v0.32.0/ast/visit.go:273 +0x5c
  github.com/open-policy-agent/opa/ast.(*GenericVisitor).Walk()
      /Users/markushinz/go/pkg/mod/github.com/open-policy-agent/opa@v0.32.0/ast/visit.go:338 +0x70c
  github.com/open-policy-agent/opa/ast.(*GenericVisitor).Walk()
      /Users/markushinz/go/pkg/mod/github.com/open-policy-agent/opa@v0.32.0/ast/visit.go:326 +0xef8
  github.com/open-policy-agent/opa/ast.WalkClosures()
      /Users/markushinz/go/pkg/mod/github.com/open-policy-agent/opa@v0.32.0/ast/visit.go:164 +0x64
  github.com/open-policy-agent/opa/ast.(*typeChecker).checkClosures()
      /Users/markushinz/go/pkg/mod/github.com/open-policy-agent/opa@v0.32.0/ast/check.go:158 +0x78
  github.com/open-policy-agent/opa/ast.(*typeChecker).CheckBody.func1()
      /Users/markushinz/go/pkg/mod/github.com/open-policy-agent/opa@v0.32.0/ast/check.go:104 +0x60
  github.com/open-policy-agent/opa/ast.WalkExprs.func1()
      /Users/markushinz/go/pkg/mod/github.com/open-policy-agent/opa@v0.32.0/ast/visit.go:208 +0x54
  github.com/open-policy-agent/opa/ast.(*GenericVisitor).Walk()
      /Users/markushinz/go/pkg/mod/github.com/open-policy-agent/opa@v0.32.0/ast/visit.go:273 +0x5c
  github.com/open-policy-agent/opa/ast.(*GenericVisitor).Walk()
      /Users/markushinz/go/pkg/mod/github.com/open-policy-agent/opa@v0.32.0/ast/visit.go:314 +0xe08
  github.com/open-policy-agent/opa/ast.WalkExprs()
      /Users/markushinz/go/pkg/mod/github.com/open-policy-agent/opa@v0.32.0/ast/visit.go:212 +0x64
  github.com/open-policy-agent/opa/ast.(*typeChecker).CheckBody()
      /Users/markushinz/go/pkg/mod/github.com/open-policy-agent/opa@v0.32.0/ast/check.go:102 +0xb8
  github.com/open-policy-agent/opa/ast.(*typeChecker).checkRule()
      /Users/markushinz/go/pkg/mod/github.com/open-policy-agent/opa@v0.32.0/ast/check.go:209 +0x390
  github.com/open-policy-agent/opa/ast.(*typeChecker).CheckTypes()
      /Users/markushinz/go/pkg/mod/github.com/open-policy-agent/opa@v0.32.0/ast/check.go:150 +0x1d4
  github.com/open-policy-agent/opa/ast.(*Compiler).checkTypes()
      /Users/markushinz/go/pkg/mod/github.com/open-policy-agent/opa@v0.32.0/ast/compile.go:1067 +0x3d0
  github.com/open-policy-agent/opa/ast.(*Compiler).checkTypes-fm()
      /Users/markushinz/go/pkg/mod/github.com/open-policy-agent/opa@v0.32.0/ast/compile.go:1060 +0x40
  github.com/open-policy-agent/opa/ast.(*Compiler).runStage()
      /Users/markushinz/go/pkg/mod/github.com/open-policy-agent/opa@v0.32.0/ast/compile.go:1088 +0x104
  github.com/open-policy-agent/opa/ast.(*Compiler).compile()
      /Users/markushinz/go/pkg/mod/github.com/open-policy-agent/opa@v0.32.0/ast/compile.go:1108 +0x124
  github.com/open-policy-agent/opa/ast.(*Compiler).Compile()
      /Users/markushinz/go/pkg/mod/github.com/open-policy-agent/opa@v0.32.0/ast/compile.go:365 +0x328

[truncated]
```

## Steps to Reproduce the Problem

* OPA version: v0.32.0
* Go version: 1.17

To reproduce one can use a test such as the following und run it with `go test -race`:

```go
func TestGetCompiler(t *testing.T) {
	modules, err := getModules(regoCode) // returns map[string]*ast.Module
	assert.NoError(t, err)
	for i := 0; i < 10; i++ {
		t.Run(fmt.Sprintf("Iteration %v", i), func(t *testing.T) {
			t.Parallel()
			_, err = getCompiler(modules)
			assert.NoError(t, err)
		})
	}
}
```

## Additional Info

The stack trace shows that `types.Compare()` causes the issue. It looks like it uses sorting algorithms that directly operate on slices. It uses https://github.com/open-policy-agent/opa/blob/4747e22f227985a1a04f21da55783469e42f037b/types/types.go#L371 which should not be accessed/modified by multiple go routines. If `types.A` is the only issue here, a solution would be to always use https://github.com/open-policy-agent/opa/blob/4747e22f227985a1a04f21da55783469e42f037b/types/types.go#L374-L380 instead.

**Comment by tsandall** [comment] 2021-09-15 22:50
@markushinz thanks for filing this.

Is it possible to share the policy that you used in your test case? I haven't bee able to reproduce the race with large -count values:

```
(fix-3793)[*]torin:~/go/src/github.com/open-policy-agent/opa$ go test -race ./ast -run TestCompileModules -count=1000
ok      github.com/open-policy-agent/opa/ast    3.860s
(fix-3793)[*]torin:~/go/src/github.com/open-policy-agent/opa$ go version
go version go1.17.1 linux/amd64
```

Test case:

```go
package ast

import (
	"fmt"
	"testing"
)

func getCompiler(modules map[string]*Module) (*Compiler, error) {
	compiler := NewCompiler()
	compiler.Compile(modules)
	if compiler.Failed() {
		return nil, compiler.Errors
	}
	return compiler, nil
}

func getModules(s string) (map[string]*Module, error) {
	module, err := ParseModule("test.rego", s)
	if err != nil {
		return nil, err
	}
	return map[string]*Module{"test.rego": module}, nil
}

func TestCompileModules(t *testing.T) {
	modules, err := getModules(`package test

	p { input.bar == input.foo }`)
	if err != nil {
		t.Fatal(err)
	}
	for i := 0; i < 10; i++ {
		t.Run(fmt.Sprint(i), func(t *testing.T) {
			t.Parallel()
			_, err := getCompiler(modules)
			if err != nil {
				t.Fatal(err)
			}
		})
	}
}
```

If you can include the full stack trace, that might also be helpful.

**Comment by markushinz** [comment] 2021-09-16 10:47
Hi @tsandall,

thanks for the quick reply. Here's a concrete example which causes the issue. Just replace `fileA` and `fileB` with the contents from GitHub.

```go
func moduleName(m *ast.Module) string {
	p := strings.Fields(m.Package.String())
	if len(p) != 2 {
		return ""
	}
	return p[len(p)-1]
}

func Test_GetCompiler(t *testing.T) {
	rules := map[string]string{
		"fileA": "https://github.com/open-policy-agent/library/blob/master/terraform/library.rego", //
		"fileB": "https://github.com/open-policy-agent/library/blob/master/terraform/input.rego",
	}
	modules := make(map[string]*ast.Module)
	for _, rule := range rules {
		module, err := ast.ParseModule("", rule)
		assert.NoError(t, err)
		modules[moduleName(module)] = module
	}

	for i := 0; i < 10; i++ {
		t.Run(fmt.Sprintf("compiler_%v", i), func(t *testing.T) {
			t.Parallel()
			compiler := ast.NewCompiler()
			compiler.Compile(modules)
			if compiler.Failed() {
				assert.NoError(t, compiler.Errors)
			}
			_, err := getCompiler(modules)
			assert.NoError(t, err)
		})
	}
}
```

**Comment by tsandall** [comment] 2021-09-16 16:39
@markushinz thanks. When I run that test case w/ the rego files inlined, I get a data race due to comments on the module not being copied: https://gist.github.com/tsandall/fc863b7a6aca1bfc6940f014a37e1a76. I'll submit a PR with a fix for that. I'm not able to reproduce the original stack trace you shared above. Can you share a stack trace from the full example you provided in your last comment?

**Comment by tsandall** [comment] 2021-09-16 16:57
@markushinz if you could try running the test locally in your environment w/ my branch linked in that PR it would be helpful because I'm not able to reproduce the original data race that you showed above. If you post the full stack trace from the race detector that would be _super_ helpful.

**Comment by srenatus** [comment] 2021-09-16 17:26
Merging the PR closed this. I suppose https://github.com/open-policy-agent/opa/issues/3793#issuecomment-921072057 would still be helpful, though @markushinz

**Comment by markushinz** [comment] 2021-09-17 10:11
@tsandall I did run the tests against your branch and it did not solve the problem. Luckily, I was able to except the rego file which causes the issues. I provided both the full go code (including rego) and the full output of `go test -race` in the following gists:

https://gist.github.com/markushinz/a46a48bf74eb8a7176c46502b89bd81c
https://gist.github.com/markushinz/e707e75036b389fcf2b4eaa72504f452

**Comment by tsandall** [comment] 2021-09-17 20:27
@markushinz thanks! that was super helpful. I've put up another PR to address the race. 🙏

**Comment by markushinz** [comment] 2021-09-20 06:04
@tsandall thanks a lot for addressing this so quickly. Looking forward to testing it once it's merged

**Comment by srenatus** [comment] 2021-09-20 09:46
✔️ @markushinz It's been merged. Please re-open if you find a chance to test this and the issue persists.

**Closed** 2021-09-20 09:46 UTC
Labels: bug

**Comment by markushinz** [comment] 2021-09-20 15:18
@srenatus @tsandall awesome all race conditions are gone! Thank you so much!
