### ISSUE TITLE
Import variable is not defined but rule is still running

### ISSUE THREAD

**Issue by NehaSachan** [open-policy-agent/opa#2672] opened 2020-08-31 10:31 UTC
//first.rego
package demo

import data.vars.limit as numeric_limit

SomeRule[result] {
x:= 100
x > numeric_limit
result := "OK"
}

//second.rego
_________________________________________

package vars

//no variable defined here.

Expected Behaviour: 
It should throw error that there is no data.vars.limit variable  OR should fail the rule with error.

ACtual Behaviour:
Its running without any error.

**Comment by tsandall** [comment] 2020-08-31 14:18
Closing this as it's a duplicate of #491.

**Closed by tsandall** 2020-08-31 14:18 UTC
