### ISSUE TITLE
RFE return details on policy evaluation failure

### ISSUE THREAD

**Issue by nhi-vanye** [open-policy-agent/opa#1148] opened 2019-01-10 09:58 UTC
It would be nice to have (human readable( details on which statement caused a policy failure returned in the API

We're using rego as a scheduling policy engine - it would be nice to be able to convey to the rest of the system if the policy failed because it was time of day, day of week or even invalid license.

I would be okay if it was up to the policy writer to label failures to minimize impact

i.e.

```
   {# does the tenant still have available licenses ? #}
    Organizations[_].licensed_count > Organizations[_].consumed_count || "No available licenses"

    {# provide policy with some standard data ? #}
    time.now_ns( now )
    [hour, minute, second] = time.clock( now )

    {# is the tennant allowed to run analysis today ? #}
    time.weekday( now ) = Rules[_].day || "Policy excludes execution on {.Rules[_].day}"

```

**Comment by tsandall** [comment] 2019-01-11 16:35
@nhi-vanye thanks for filing this issue! This kind of feature has come up [before](https://github.com/open-policy-agent/opa/issues/729). We've kicked around different ways that it could be implemented.

We're busy with the current roadmap through February but I could easily see prioritizing this in the next couple months.

We'll need to evaluate different options for the feature and implementation before we commit to something.

**Comment by jonatanblue** [comment] 2019-01-29 08:47
Yes, very much yes. This is critical if you want users to be able to act on the error messages.

There may be arguments for hiding the failure root cause for security reasons, but in most implementations if the user has to supply 10 or so options and doesn’t know which one is incorrect, it is a must to point them in the right direction.

**Comment by tsandall** [comment] 2019-02-19 21:55
One option is to generate the error messages inside the policy:

```
package example

decision = {"allowed": true} {
  count(deny) == 0
}

decision = {"allowed": false, "reason": reason} {
  count(deny) > 0
  reason := concat(", ", deny)
}

deny["no available licenses"] {
  data.orgs[input.user.org].license_count >= data.orgs[input.user.org].consumed_count 
}

deny["analysis cannot run today"] {
  input.action == "RunAnalysis"
  time.weekday(time.now_ns()) != "Tuesday"
}
```

The service integrating with OPA would query for the `example/decision`.

**Comment by jonatanblue** [comment] 2019-02-20 04:47
This is brilliant. Thanks!

**Comment by tsandall** [comment] 2019-04-12 18:45
Closing for now. I think we have a reasonable solution that doesn't entail changes to the language.

**Closed by tsandall** 2019-04-12 18:45 UTC
Labels: feature-request
