### ISSUE TITLE
OPA eval --disable-inlining can not parse parameters with double quotes

### ISSUE THREAD

**Issue by xin-styra** [open-policy-agent/opa#2196] opened 2020-03-17 21:34 UTC
# Expected Behavior
OPA command line should be able to parse parameters with double-quotes.  E.g., --disable-inlining=query should take the query even if there are double quotes `"` in the query, e.g., data.policy["com.styra.envoy"].resolver.main

# Actual Behavior
It seems when partial eval is executed, the above parameter query is not respected. There seems to be some problem with argument parsing for those with quotes.

# Steps to Reproduce the Problem

  1.  Given any policy bundle 
  2. Run opa eval -p -b . 'x = [actual query]' -f source --disable-inlining=query
  3. This works if I use Golang to execute the partial eval with the same parameters. 

# Additional Info

**Comment by patrick-east** [comment] 2020-03-17 21:43
Easy repro:

```bash
opa eval --disable-inlining='data["p"]' data
```
Gives:
```
Error: invalid argument "data[\"p\"]" for "--disable-inlining" flag: parse error on line 1, column 5: bare " in non-quoted-field
Usage:
  opa eval <query> [flags]

Flags:
  -b, --bundle string                                 set bundle file(s) or directory path(s)
      --coverage                                      report coverage
  -d, --data string                                   set data file(s) or directory path(s)
      --disable-indexing                              disable indexing optimizations
      --disable-inlining strings                      set paths of documents to exclude from inlining
      --explain {off,full,notes,fails}                enable query explanations (default off)
      --fail                                          exits with non-zero exit code on undefined/empty result and errors
      --fail-defined                                  exits with non-zero exit code on defined/non-empty result and errors
  -f, --format {json,values,bindings,pretty,source}   set output format (default json)
  -h, --help                                          help for eval
      --ignore strings                                set file and directory names to ignore during loading (e.g., '.*' excludes hidden files)
      --import string                                 set query import(s)
  -i, --input string                                  set input file path
      --instrument                                    enable query instrumentation metrics (implies --metrics)
      --metrics                                       report query performance metrics
      --package string                                set query package
  -p, --partial                                       perform partial evaluation
      --pretty-limit int                              set limit after which pretty output gets truncated (default 80)
      --profile                                       perform expression profiling
      --profile-limit int                             set number of profiling results to show (default 10)
      --profile-sort string                           set sort order of expression profiler results
      --stdin                                         read query from stdin
  -I, --stdin-input                                   read input document from stdin
  -u, --unknowns strings                              set paths to treat as unknown during partial evaluation (default [input])

invalid argument "data[\"p\"]" for "--disable-inlining" flag: parse error on line 1, column 5: bare " in non-quoted-field
```

**Comment by sresthas** [comment] 2020-04-30 20:11
Can I take this up? Some pointers would be helpful

**Comment by patrick-east** [comment] 2020-04-30 22:09
@sresthas Sounds good. This one will require digging into some of the documentation and code for https://github.com/spf13/cobra 

I think the first thing to confirm is where the error is happening and _why_.

Based on the error message I think the problem is with the CLI argument string for https://github.com/open-policy-agent/opa/blob/9d1b42d07a156307ff0ef5bc4ddd9ce17c9b6975/cmd/eval.go#L221 and passing in a flag value like `--disable-inlining='data["p"]'`

But it is not clear why this is a problem.

**Comment by Syn3rman** [comment] 2020-05-07 14:19
Hey @patrick-east,

Since there has been no update on this for a while, could I have a look at it later? (after closing the open pr)

**Comment by sresthas** [comment] 2020-05-07 14:42
@Syn3rman I am looking into this, can you please select any other issue. 
Thanks!

**Comment by Syn3rman** [comment] 2020-05-19 09:00
Using `StringArrayVarP` instead of `StringSliceVarP` seems to do the trick here. Should I make the changes and open a pr @patrick-east?

**Comment by patrick-east** [comment] 2020-05-19 17:54
Go for it

**Closed** 2020-05-27 12:44 UTC
Labels: bug, help wanted, low-hanging-fruit
