### ISSUE TITLE
opa test with multiple dirs provided as absolute path does not work as expected 

### ISSUE THREAD

**Issue by yeDor** [open-policy-agent/opa#3442] opened 2021-05-07 07:10 UTC
this works as expected:
`opa test src/main/rego src/test/rego -f pretty -v`

but giving the full path to the same folder structure produces failed tests
`opa test  D:\workspace\project\src\main\rego D:\workspace\project\src\test\rego -f pretty -v`

## Expected Behavior
no difference if absolute or relative path provided

## Actual Behavior
absolute path does not works as expected

Version: 0.28.0
Build Commit: 3fbcd71
Build Timestamp: 2021-04-27T13:51:58Z
Build Hostname: c8a0b3ab05bf
Go Version: go1.15.8
WebAssembly: unavailable

**Comment by anderseknert** [comment] 2021-05-07 07:47
There seems to be more than just relative vs. absolute directories at play here as you change `/` to `\` in your absolute path. I take it this is a CMD shell? I don't have a Windows machine to test now but I can use `opa test /abs1 /abs2 /abs3` here on my Mac without problems.

**Comment by tsandall** [comment] 2021-05-19 12:56
I tried to quickly reproduce this but failed:

```
PS C:\Users\torin\workspace\test-exp> C:\Users\torin\go\opa\opa.exe test .\a .\b
PASS: 1/1
PS C:\Users\torin\workspace\test-exp> C:\Users\torin\go\opa\opa.exe test C:\Users\torin\workspace\test-exp\a C:\Users\torin\workspace\test-exp\b
PASS: 1/1
PS C:\Users\torin\workspace\test-exp> C:\Users\torin\go\opa\opa.exe version
Version: 0.28.0
Build Commit:
Build Timestamp:
Build Hostname:
Go Version: go1.14.3
WebAssembly: unavailable
```

**Comment by anderseknert** [comment] 2021-06-15 20:21
@yeDor this still a problem or did you manage to figure it out / work around it? Closing issue for now and will re-open if needed.

**Closed by anderseknert** 2021-06-15 20:21 UTC
Labels: bug, waiting-for-response

**Comment by yeDor** [comment] 2021-08-23 07:51
Hello @anderseknert, thanks for you response and investigation. Yes, i still see the problem. Here i prepared some test example https://github.com/yeDor/opa_issues_3442

With absolute path:
```
D:\Temp\opa_issues_3442>opa test D:\Temp\opa_issues_3442\src\main\rego D:\Temp\opa_issues_3442\src\test\rego -f pretty -v
FAILURES
--------------------------------------------------------------------------------
data.something.test_data_something: FAIL (0s)


  query:1                                                        Enter data.something.test_data_something = _
  \Temp\opa_issues_3442\src\test\rego\test_something.rego:15     | Enter data.something.test_data_something
  \Temp\opa_issues_3442\src\main\rego\user-service.rego:7        | | Enter data.something.data_something
  \Temp\opa_issues_3442\src\main\rego\user-service.rego:8        | | | Fail input.action = data.body.something
  \Temp\opa_issues_3442\src\test\rego\test_something.rego:16     | | Fail data.something.data_something with input as {"action": "test"}
  query:1                                                        | Fail data.something.test_data_something = _

SUMMARY
--------------------------------------------------------------------------------
data.something.test_something: PASS (0s)
data.something.test_not_something: PASS (0s)
data.something.test_data_something: FAIL (0s)
data.something.test_not_data_something: PASS (0s)
--------------------------------------------------------------------------------
PASS: 3/4
FAIL: 1/4
```
With relative path:
```
D:\Temp\opa_issues_3442>opa test src\main\rego src\test\rego -f pretty -v
data.something.test_something: PASS (1ms)
data.something.test_not_something: PASS (0s)
data.something.test_data_something: PASS (0s)
data.something.test_not_data_something: PASS (0s)
--------------------------------------------------------------------------------
PASS: 4/4
```

looks like it has something to do with data.json
```
D:\Temp\opa_issues_3442>opa version
Version: 0.28.0
Build Commit: 3fbcd71
Build Timestamp: 2021-04-27T13:51:58Z
Build Hostname: c8a0b3ab05bf
Go Version: go1.15.8
WebAssembly: unavailable
```

**Comment by ashutosh-narkar** [comment] 2021-08-23 17:11
Thanks @yeDor for your response. Are you seeing this issue with a recent release of OPA as well ? It would be great if you could provide info on that.

**Comment by ashutosh-narkar** [comment] 2021-08-23 17:57
@yeDor can you confirm your tests are passing with the relative path. I'm getting the below error:
```
$ opa test .  -v
FAILURES
--------------------------------------------------------------------------------
data.something.test_data_something: FAIL (103.315µs)

  query:1                                  Enter data.something.test_data_something = _
  src/test/rego/test_something.rego:15     | Enter data.something.test_data_something
  src/main/rego/user-service.rego:7        | | Enter data.something.data_something
  src/main/rego/user-service.rego:8        | | | Fail input.action = data.body.something
  src/test/rego/test_something.rego:16     | | Fail data.something.data_something with input as {"action": "test"}
  query:1                                  | Fail data.something.test_data_something = _

SUMMARY
--------------------------------------------------------------------------------
data.something.test_something: PASS (3.233757ms)
data.something.test_not_something: PASS (123.658µs)
data.something.test_data_something: FAIL (103.315µs)
data.something.test_not_data_something: PASS (139.416µs)
--------------------------------------------------------------------------------
PASS: 3/4
FAIL: 1/4
```
