### ISSUE TITLE
Allow reference operator in more places

### ISSUE THREAD

**Issue by jaspervdj** [open-policy-agent/opa#1868] opened 2019-10-29 16:55 UTC
# Expected Behavior

I would like to use the reference operator (`[x]` or `.foo`) in more places, such as:

 -  After partial rules, e.g. `split("foo.bar", ".")[1]`
 -  After array/set/object terms, e.g. `[1, 2, 3][i]` or `{"foo": 1}.foo`

# Actual Behavior

Currently, these are not accepted by the parser:

```
> split("foo.bar", ".")[1]
|
1 error occurred: 1:1: rego_parse_error: partial rules cannot take arguments
        split("foo.bar", ".")[1]
        ^
>
```

# Steps to Reproduce the Problem

See above.

# Additional Info

I am happy to implement this, and my intention is to do this in two steps:

 1. Update the parser and AST to allow this.
 2. Add a `RewriteNestedReferences` (not sure about this name) pass in `ast/compile.go`.

The pass would work by assigning auxiliary a local variable to the left-hand side of the reference, and then using this local variable in a follow-up reference.  For example:

```
split("foo.bar", ".")[1]
 => __local_var_0 = split("foo.bar", ".")
    __local_var_0[1]
```

These rewrite semantics work well with references that introduce variables:

```
split("foo.bar", ".")[i]
 => __local_var_0 = split("foo.bar", ".")
    __local_var_0[i]
```

Lastly, they also work in a nested fashion, with the caveat that the most deeply nested references need to be assigned first:

```
split(split("foo.bar:qux", ".")[_], ":")[i]
 => __local_var_0 = split("foo.bar:qux", ".")
    __local_var_1 = split(__local_var_0[_], ":")
    __local_var_1[i]
```

**Comment by tsandall** [comment] 2020-01-09 16:36
I haven't had a chance to look into this yet but it seems that we missed a case in our testing:

```
> f(x) = [x] { true }
Rule 'f' defined in package repl. Type 'show' to see rules.
> f(1)[0]
1 error occurred: 1:1: rego_type_error: undefined function f
```

Once this issue is fixed we can close this issue. I'll try to look into this in the next couple days.

**Comment by jaspervdj-luminal** [comment] 2020-01-09 21:16
I gave this a quick look and it seems that the problem is that we're not resolving references correctly in this case.  I'll prepare a PR.

**Closed** 2020-01-14 20:58 UTC
Labels: enhancement
